import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter });

const herbs = [
  {
    name: "Basil",
    scientificName: "Ocimum basilicum",
    category: "Culinary",
    summary: "A fragrant, warm-weather kitchen herb central to Italian and Southeast Asian cooking.",
    uses: "Pesto, Tomato dishes, Teas, Aromatherapy",
    properties: "May help reduce inflammation, Antioxidant, May fight bacteria",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/basil.jpg",
  },
  {
    name: "Chamomile",
    scientificName: "Matricaria chamomilla",
    category: "Medicinal",
    summary: "A daisy-like flower, usually made into tea, traditionally used for relaxation and digestive comfort.",
    uses: "Sleep, Calming tea, Soothing skin",
    properties: "Mildly relaxing, May help reduce inflammation, May ease cramps",
    cautions: "May cause an allergic reaction in people allergic to ragweed.",
    imageUrl: "/herbs/chamomile.jpg",
  },
  {
    name: "Peppermint",
    scientificName: "Mentha piperita",
    category: "Medicinal",
    summary: "A cooling, menthol-rich herb traditionally used for digestion and headaches. Research suggests peppermint oil may help IBS symptoms.",
    uses: "Digestive tea, Headaches, Aromatherapy",
    properties: "May ease cramps, May relieve pain, May relieve gas",
    cautions: "Can make acid reflux worse in some people.",
    imageUrl: "/herbs/peppermint.jpg",
  },
  {
    name: "Rosemary",
    scientificName: "Salvia rosmarinus",
    category: "Culinary",
    summary: "A woody, pine-scented kitchen herb popular in roasted dishes and hair care.",
    uses: "Roasted meats and vegetables, Hair rinses, Memory",
    properties: "Antioxidant, May fight germs, May boost circulation",
    cautions: "High doses may cause contractions of the womb; avoid during pregnancy.",
    imageUrl: "/herbs/rosemary.jpg",
  },
  {
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    category: "Aromatic",
    summary: "A purple-flowered herb prized for its scent and traditionally used to relax.",
    uses: "Aromatherapy, Sleep, Skin care",
    properties: "May ease anxiety, Calming, May fight germs",
    cautions: "Don't swallow the essential oil undiluted.",
    imageUrl: "/herbs/lavender.jpg",
  },
  {
    name: "Ginger",
    scientificName: "Zingiber officinale",
    category: "Medicinal",
    summary: "A spicy, warming root traditionally used for nausea and inflammation. Research suggests it may help with nausea during pregnancy.",
    uses: "Nausea, Teas, Cooking, Inflammation",
    properties: "May ease nausea, May help reduce inflammation, Aids digestion",
    cautions: "May interact with blood-thinning medicines at high doses.",
    imageUrl: "/herbs/ginger.jpg",
  },
  {
    name: "Echinacea",
    scientificName: "Echinacea purpurea",
    category: "Medicinal",
    summary: "A purple coneflower traditionally used to support the immune system, especially for colds.",
    uses: "Colds and flu, Tinctures, Teas",
    properties: "May stimulate the immune system, May help reduce inflammation",
    cautions: "Not recommended for people with autoimmune conditions without medical advice.",
    imageUrl: "/herbs/echinacea.jpg",
  },
  {
    name: "Thyme",
    scientificName: "Thymus vulgaris",
    category: "Culinary",
    summary: "A small-leaved, earthy herb used widely in savory cooking and traditionally in cough remedies.",
    uses: "Soups and stews, Coughs, Germ-fighting gargle",
    properties: "May fight germs, May loosen mucus, May ease cramps",
    cautions: "The essential oil is strong; use it diluted.",
    imageUrl: "/herbs/thyme.jpg",
  },
  {
    name: "Sage",
    scientificName: "Salvia officinalis",
    category: "Culinary",
    summary: "A silvery-leaved kitchen herb with a savory, slightly peppery flavor, traditionally used for sore throats and indigestion.",
    uses: "Stuffing and sausages, Sore throat gargle, Memory",
    properties: "Antioxidant, May fight germs, Astringent (tightens tissues)",
    cautions: "Avoid large medicinal doses during pregnancy.",
    imageUrl: "/herbs/sage.jpg",
  },
  {
    name: "Turmeric",
    scientificName: "Curcuma longa",
    category: "Medicinal",
    summary: "A golden root used in curries, known for its natural compound curcumin and traditionally used for inflammation.",
    uses: "Curries, Golden milk, Joints",
    properties: "May help reduce inflammation, Antioxidant",
    cautions: "May interact with blood thinners; high doses can upset the stomach.",
    imageUrl: "/herbs/turmeric.jpg",
  },
  {
    name: "Lemon Balm",
    scientificName: "Melissa officinalis",
    category: "Medicinal",
    summary: "A lemon-scented relative of mint, traditionally used to ease stress and help with sleep.",
    uses: "Calming tea, Stress, Cold sores (on the skin)",
    properties: "Mildly relaxing, May fight viruses, May relieve gas",
    cautions: "May interact with thyroid medicines.",
    imageUrl: "/herbs/lemon-balm.jpg",
  },
  {
    name: "Dill",
    scientificName: "Anethum graveolens",
    category: "Culinary",
    summary: "A feathery, tangy kitchen herb often paired with fish and pickles. Its seeds are traditionally used for gas and upset stomach.",
    uses: "Pickling, Fish dishes, Digestive tea",
    properties: "May relieve gas, May ease mild cramps",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/dill.jpg",
  },
  {
    name: "Valerian",
    scientificName: "Valeriana officinalis",
    category: "Medicinal",
    summary: "A root traditionally used to help with sleep.",
    uses: "Sleep, Anxiety",
    properties: "May make you sleepy, May ease anxiety",
    cautions: "Can cause drowsiness; don't combine with alcohol or sedatives.",
    imageUrl: "/herbs/valerian.jpg",
  },
  {
    name: "Oregano",
    scientificName: "Origanum vulgare",
    category: "Culinary",
    summary: "A pungent Mediterranean kitchen herb central to pizza and pasta sauces.",
    uses: "Italian and Greek cooking, Oregano oil",
    properties: "May fight germs, Antioxidant",
    cautions: "Oregano oil is strong and should be diluted.",
    imageUrl: "/herbs/oregano.jpg",
  },
  {
    name: "Nettle",
    scientificName: "Urtica dioica",
    category: "Medicinal",
    summary: "A stinging plant eaten as a spring vegetable and traditionally used for joint pain and urinary complaints.",
    uses: "Allergy tea, Nourishing infusions",
    properties: "May help reduce inflammation, May increase urination, Nourishing",
    cautions: "The fresh plant stings the skin; cook or dry it before use.",
    imageUrl: "/herbs/nettle.jpg",
  },
  {
    name: "Cilantro",
    scientificName: "Coriandrum sativum",
    category: "Culinary",
    summary: "A fresh, citrusy kitchen herb. Its seeds, sold as coriander, are traditionally used to support digestion.",
    uses: "Salsas, Curries, Garnish",
    properties: "Antioxidant, Mild digestive aid",
    cautions: "Some people find it tastes soapy because of their genes.",
    imageUrl: "/herbs/cilantro.jpg",
  },
  {
    name: "St. John's Wort",
    scientificName: "Hypericum perforatum",
    category: "Medicinal",
    summary: "A yellow-flowered herb traditionally used to support mood. It interacts with many common medicines.",
    uses: "Low mood, Wound salves (on the skin)",
    properties: "Antidepressant-like, May help reduce inflammation",
    cautions: "Interacts with many medicines, including antidepressants and birth control pills.",
    imageUrl: "/herbs/st-johns-wort.jpg",
  },
  {
    name: "Fennel",
    scientificName: "Foeniculum vulgare",
    category: "Culinary",
    summary: "An anise-flavored plant whose seeds and bulb are both widely eaten. The seeds are traditionally used for digestion.",
    uses: "Digestive tea, Salads, Roasted bulb dishes",
    properties: "May relieve gas, Mild estrogen-like effects, May ease cramps",
    cautions: "Avoid concentrated forms during pregnancy.",
    imageUrl: "/herbs/fennel.jpg",
  },
  {
    name: "Ashwagandha",
    scientificName: "Withania somnifera",
    category: "Medicinal",
    summary: "A root from Ayurvedic medicine, traditionally used to help the body cope with stress.",
    uses: "Stress, Sleep, Energy",
    properties: "Adaptogen, Calming, May help reduce inflammation",
    cautions: "Avoid during pregnancy and with certain thyroid or autoimmune conditions.",
    imageUrl: "/herbs/ashwagandha.jpg",
  },
  {
    name: "Parsley",
    scientificName: "Petroselinum crispum",
    category: "Culinary",
    summary: "A versatile, mild kitchen herb used as both a garnish and a flavor base.",
    uses: "Garnish, Tabbouleh, Stocks and sauces",
    properties: "May increase urination, Rich in vitamins K and C",
    cautions: "Avoid medicinal doses (not cooking amounts) during pregnancy.",
    imageUrl: "/herbs/parsley.jpg",
  },
  {
    name: "Garlic",
    scientificName: "Allium sativum",
    category: "Culinary",
    summary: "A pungent kitchen bulb traditionally used for heart and circulation health. Research suggests garlic supplements may lower blood pressure and cholesterol a little.",
    uses: "Cooking, High blood pressure, Cholesterol, Colds",
    properties: "May lower blood pressure slightly, May lower cholesterol slightly",
    cautions: "Garlic supplements may raise bleeding risk; stop 7 days before surgery and check with a doctor if you take blood thinners.",
    imageUrl: "/herbs/garlic.jpg",
  },
  {
    name: "Hawthorn",
    scientificName: "Crataegus monogyna",
    category: "Medicinal",
    summary: "A flowering shrub of the rose family, traditionally used for the heart. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Heart health, Circulation, Stress",
    properties: "Heart support (traditional), Calming",
    cautions: "Heart symptoms need a doctor's diagnosis first; may interact with heart medicines.",
    imageUrl: "/herbs/hawthorn.jpg",
  },
  {
    name: "Ginseng",
    scientificName: "Panax ginseng",
    category: "Medicinal",
    summary: "A root long used in traditional Chinese medicine as a calming herb and an adaptogen. Research on its effects is mixed.",
    uses: "Energy, Thinking and focus, Blood sugar",
    properties: "Adaptogen, Calming",
    cautions: "May lower blood sugar and affect blood clotting; not for children or during pregnancy or breastfeeding.",
    imageUrl: "/herbs/ginseng.jpg",
  },
  {
    name: "Ginkgo",
    scientificName: "Ginkgo biloba",
    category: "Medicinal",
    summary: "Leaves of the ginkgo tree, sometimes called the fossil tree, traditionally used in Europe for minor circulation problems and in Chinese medicine for cough.",
    uses: "Circulation, Cold hands and feet, Memory",
    properties: "Circulation support, Memory support",
    cautions: "May increase bleeding risk, especially with blood thinners; fresh seeds are poisonous.",
    imageUrl: "/herbs/ginkgo.jpg",
  },
  {
    name: "Gynostemma",
    scientificName: "Gynostemma pentaphyllum",
    category: "Medicinal",
    summary: "A plant from the cucumber family, known in China as jiaogulan and used in traditional medicine and teas. It has been studied for lowering cholesterol.",
    uses: "Tea, Cholesterol",
    properties: "May lower cholesterol",
    cautions: "Research on its safety is limited, though no serious side effects were reported in trials.",
    imageUrl: "/herbs/gynostemma.jpg",
  },
  {
    name: "Reishi",
    scientificName: "Ganoderma lucidum",
    category: "Medicinal",
    summary: "A mushroom prized for centuries in traditional Chinese, Japanese and Korean medicine. A Cochrane review found it didn't lower heart disease risk factors.",
    uses: "Energy, Immune support, Heart health",
    properties: "Immune support",
    cautions: "Liver damage has been reported; may raise bleeding risk with blood thinners.",
    imageUrl: "/herbs/reishi.jpg",
  },
  {
    name: "Motherwort",
    scientificName: "Leonurus cardiaca",
    category: "Medicinal",
    summary: "A plant from the mint family, traditionally used as a heart tonic and for women's health. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Nervous tension, Women's health",
    properties: "Calming, Heart tonic",
    cautions: "Must not be taken during pregnancy; may increase bleeding risk with blood thinners.",
    imageUrl: "/herbs/motherwort.jpg",
  },
  {
    name: "Linden",
    scientificName: "Tilia cordata",
    category: "Medicinal",
    summary: "Flowers of the lime (linden) tree, traditionally made into tea for colds, stress and nervous heart complaints.",
    uses: "Tea, Colds, Stress, Palpitations",
    properties: "Calming",
    cautions: "Some sources advise people with heart conditions to avoid it; not recommended during pregnancy.",
    imageUrl: "/herbs/linden.jpg",
  },
  {
    name: "Hibiscus",
    scientificName: "Hibiscus sabdariffa",
    category: "Medicinal",
    summary: "The tart red calyces of this flower are made into a tea known as roselle or sour tea. Reviews of trials suggest it may lower blood pressure.",
    uses: "Tea, High blood pressure, Cholesterol",
    properties: "May lower blood pressure, Antioxidant",
    cautions: "How it interacts with blood pressure medicines and water pills hasn't been fully studied; check with your doctor.",
    imageUrl: "/herbs/hibiscus.jpg",
  },
  {
    name: "Flaxseed",
    scientificName: "Linum usitatissimum",
    category: "Culinary",
    summary: "Small seeds rich in fiber and the omega-3 fat ALA, eaten whole, ground or as oil. Research suggests flaxseed may lower blood pressure and cholesterol slightly.",
    uses: "Food, Constipation, Blood pressure, Cholesterol",
    properties: "Gentle laxative, May lower cholesterol slightly",
    cautions: "Don't eat raw or unripe seeds; not for people with swallowing problems or a blocked gut.",
    imageUrl: "/herbs/flaxseed.jpg",
  },
  {
    name: "Cinnamon",
    scientificName: "Cinnamomum verum",
    category: "Culinary",
    summary: "A warm kitchen spice made from tree bark, traditionally used for digestive complaints. Research on its effects on blood sugar and cholesterol is mixed.",
    uses: "Baking and cooking, Digestion, Blood sugar",
    properties: "May relieve gas and bloating",
    cautions: "Cassia cinnamon contains coumarin, which has been linked to liver problems; avoid large amounts during pregnancy.",
    imageUrl: "/herbs/cinnamon.jpg",
  },
  {
    name: "Cerasee",
    scientificName: "Momordica charantia",
    category: "Medicinal",
    summary: "A bitter plant known in Jamaica as cerasee and elsewhere as bitter melon, widely used as a folk remedy for diabetes and high blood pressure.",
    uses: "Blood sugar, High blood pressure",
    properties: "May lower blood sugar",
    cautions: "May add to the effects of diabetes medicines; avoid during pregnancy.",
    imageUrl: "/herbs/cerasee.jpg",
  },
  {
    name: "Red Clover",
    scientificName: "Trifolium pratense",
    category: "Medicinal",
    summary: "A pink-flowered clover traditionally used for skin problems and whooping cough. It has been studied for menopausal hot flashes, with inconsistent results.",
    uses: "Menopause, Skin care",
    properties: "Plant estrogens (isoflavones)",
    cautions: "May increase bleeding risk; avoid with hormone-sensitive cancers, blood thinners, or during pregnancy.",
    imageUrl: "/herbs/red-clover.jpg",
  },
  {
    name: "Raspberry Leaf",
    scientificName: "Rubus idaeus",
    category: "Medicinal",
    summary: "Leaves of the raspberry plant, made into tea. Traditionally used for period cramps and widely used in pregnancy, though its safety in pregnancy hasn't been proven.",
    uses: "Tea, Period cramps, Pregnancy (traditional)",
    properties: "May ease period cramps",
    cautions: "Not proven safe in pregnancy; ask your midwife or doctor first.",
    imageUrl: "/herbs/raspberry-leaf.jpg",
  },
  {
    name: "Chasteberry",
    scientificName: "Vitex agnus-castus",
    category: "Medicinal",
    summary: "The berries of the chaste tree (vitex), recognized in Europe for easing PMS (premenstrual syndrome).",
    uses: "PMS, Breast tenderness, Women's health",
    properties: "May ease PMS",
    cautions: "Not for use during pregnancy or breastfeeding, or with hormone-sensitive cancers.",
    imageUrl: "/herbs/chasteberry.jpg",
  },
  {
    name: "Black Cohosh",
    scientificName: "Actaea racemosa",
    category: "Medicinal",
    summary: "A root used traditionally by Native Americans and recognized in Europe for menopausal hot flushes. Rare liver problems have been reported.",
    uses: "Menopause, Hot flashes",
    properties: "May ease hot flashes",
    cautions: "Stop and see a doctor if you notice dark urine, yellow skin or eyes, or unusual tiredness.",
    imageUrl: null,
  },
  {
    name: "Dong Quai",
    scientificName: "Angelica sinensis",
    category: "Medicinal",
    summary: "A root that is one of the most widely used herbs in traditional Chinese medicine for women's health, including period pain and menopause.",
    uses: "Period pain, Menopause, Women's health",
    properties: "Women's tonic (traditional)",
    cautions: "May increase bleeding with blood thinners; avoid during pregnancy and breastfeeding.",
    imageUrl: "/herbs/dong-quai.jpg",
  },
  {
    name: "Shatavari",
    scientificName: "Asparagus racemosus",
    category: "Medicinal",
    summary: "A root used in Ayurveda as a tonic and to increase breast milk. Research on it is limited.",
    uses: "Breast milk, Menopause, Women's health",
    properties: "Tonic, May increase breast milk (traditional)",
    cautions: "Its safety in pregnancy is uncertain; ask your doctor or midwife first.",
    imageUrl: "/herbs/shatavari.jpg",
  },
  {
    name: "Queen Anne's Lace",
    scientificName: "Daucus carota",
    category: "Medicinal",
    summary: "Wild carrot, whose seeds have long been used in folk medicine to prevent pregnancy. It hasn't been proven safe or effective, and it looks like deadly poison hemlock.",
    uses: "Traditional birth control, Urinary complaints",
    properties: "Traditionally used to prevent pregnancy",
    cautions: "Not reliable birth control; avoid if pregnant or trying to conceive; easily confused with poison hemlock.",
    imageUrl: "/herbs/queen-annes-lace.jpg",
  },
  {
    name: "Maca",
    scientificName: "Lepidium meyenii",
    category: "Medicinal",
    summary: "A root vegetable from the high Andes of Peru, used for centuries as food and to boost energy and fertility. Its effects haven't been proven in rigorous trials.",
    uses: "Energy, Fertility, Sexual health, Menopause",
    properties: "Adaptogen",
    cautions: "Avoid during pregnancy and breastfeeding; may affect testosterone blood tests.",
    imageUrl: "/herbs/maca.jpg",
  },
];

async function main() {
  for (const herb of herbs) {
    await prisma.herb.upsert({
      where: { name: herb.name },
      update: herb,
      create: herb,
    });
  }
  console.log(`Seeded ${herbs.length} herbs.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
