import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter });

const herbs = [
  {
    name: "Basil",
    scientificName: "Ocimum basilicum",
    category: "Culinary",
    summary: "A fragrant, warm-weather kitchen herb central to Italian and Southeast Asian cooking.",
    uses: "Pesto, Tomato dishes, Teas, Aromatherapy",
    properties: "May help reduce inflammation, Antioxidant, May fight bacteria",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/basil.jpg",
  },
  {
    name: "Chamomile",
    scientificName: "Matricaria chamomilla",
    category: "Medicinal",
    summary: "A daisy-like flower, usually made into tea, traditionally used for relaxation and digestive comfort.",
    uses: "Sleep, Calming tea, Soothing skin",
    properties: "Mildly relaxing, May help reduce inflammation, May ease cramps",
    cautions: "May cause an allergic reaction in people allergic to ragweed.",
    imageUrl: "/herbs/chamomile.jpg",
  },
  {
    name: "Peppermint",
    scientificName: "Mentha piperita",
    category: "Medicinal",
    summary: "A cooling, menthol-rich herb traditionally used for digestion and headaches. Research suggests peppermint oil may help IBS symptoms.",
    uses: "Digestive tea, Headaches, Aromatherapy",
    properties: "May ease cramps, May relieve pain, May relieve gas",
    cautions: "Can make acid reflux worse in some people.",
    imageUrl: "/herbs/peppermint.jpg",
  },
  {
    name: "Rosemary",
    scientificName: "Salvia rosmarinus",
    category: "Culinary",
    summary: "A woody, pine-scented kitchen herb popular in roasted dishes and hair care.",
    uses: "Roasted meats and vegetables, Hair rinses, Memory",
    properties: "Antioxidant, May fight germs, May boost circulation",
    cautions: "High doses may cause contractions of the womb; avoid during pregnancy.",
    imageUrl: "/herbs/rosemary.jpg",
  },
  {
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    category: "Aromatic",
    summary: "A purple-flowered herb prized for its scent and traditionally used to relax.",
    uses: "Aromatherapy, Sleep, Skin care",
    properties: "May ease anxiety, Calming, May fight germs",
    cautions: "Don't swallow the essential oil undiluted.",
    imageUrl: "/herbs/lavender.jpg",
  },
  {
    name: "Ginger",
    scientificName: "Zingiber officinale",
    category: "Medicinal",
    summary: "A spicy, warming root traditionally used for nausea and inflammation. Research suggests it may help with nausea during pregnancy.",
    uses: "Nausea, Teas, Cooking, Inflammation",
    properties: "May ease nausea, May help reduce inflammation, Aids digestion",
    cautions: "May interact with blood-thinning medicines at high doses.",
    imageUrl: "/herbs/ginger.jpg",
  },
  {
    name: "Echinacea",
    scientificName: "Echinacea purpurea",
    category: "Medicinal",
    summary: "A purple coneflower traditionally used to support the immune system, especially for colds.",
    uses: "Colds and flu, Tinctures, Teas",
    properties: "May stimulate the immune system, May help reduce inflammation",
    cautions: "Not recommended for people with autoimmune conditions without medical advice.",
    imageUrl: "/herbs/echinacea.jpg",
  },
  {
    name: "Thyme",
    scientificName: "Thymus vulgaris",
    category: "Culinary",
    summary: "A small-leaved, earthy herb used widely in savory cooking and traditionally in cough remedies.",
    uses: "Soups and stews, Coughs, Germ-fighting gargle",
    properties: "May fight germs, May loosen mucus, May ease cramps",
    cautions: "The essential oil is strong; use it diluted.",
    imageUrl: "/herbs/thyme.jpg",
  },
  {
    name: "Sage",
    scientificName: "Salvia officinalis",
    category: "Culinary",
    summary: "A silvery-leaved kitchen herb with a savory, slightly peppery flavor, traditionally used for sore throats and indigestion.",
    uses: "Stuffing and sausages, Sore throat gargle, Memory",
    properties: "Antioxidant, May fight germs, Astringent (tightens tissues)",
    cautions: "Avoid large medicinal doses during pregnancy.",
    imageUrl: "/herbs/sage.jpg",
  },
  {
    name: "Turmeric",
    scientificName: "Curcuma longa",
    category: "Medicinal",
    summary: "A golden root used in curries, known for its natural compound curcumin and traditionally used for inflammation.",
    uses: "Curries, Golden milk, Joints",
    properties: "May help reduce inflammation, Antioxidant",
    cautions: "May interact with blood thinners; high doses can upset the stomach.",
    imageUrl: "/herbs/turmeric.jpg",
  },
  {
    name: "Lemon Balm",
    scientificName: "Melissa officinalis",
    category: "Medicinal",
    summary: "A lemon-scented relative of mint, traditionally used to ease stress and help with sleep.",
    uses: "Calming tea, Stress, Cold sores (on the skin)",
    properties: "Mildly relaxing, May fight viruses, May relieve gas",
    cautions: "May interact with thyroid medicines.",
    imageUrl: "/herbs/lemon-balm.jpg",
  },
  {
    name: "Dill",
    scientificName: "Anethum graveolens",
    category: "Culinary",
    summary: "A feathery, tangy kitchen herb often paired with fish and pickles. Its seeds are traditionally used for gas and upset stomach.",
    uses: "Pickling, Fish dishes, Digestive tea",
    properties: "May relieve gas, May ease mild cramps",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/dill.jpg",
  },
  {
    name: "Valerian",
    scientificName: "Valeriana officinalis",
    category: "Medicinal",
    summary: "A root traditionally used to help with sleep.",
    uses: "Sleep, Anxiety",
    properties: "May make you sleepy, May ease anxiety",
    cautions: "Can cause drowsiness; don't combine with alcohol or sedatives.",
    imageUrl: "/herbs/valerian.jpg",
  },
  {
    name: "Oregano",
    scientificName: "Origanum vulgare",
    category: "Culinary",
    summary: "A pungent Mediterranean kitchen herb central to pizza and pasta sauces.",
    uses: "Italian and Greek cooking, Oregano oil",
    properties: "May fight germs, Antioxidant",
    cautions: "Oregano oil is strong and should be diluted.",
    imageUrl: "/herbs/oregano.jpg",
  },
  {
    name: "Nettle",
    scientificName: "Urtica dioica",
    category: "Medicinal",
    summary: "A stinging plant eaten as a spring vegetable and traditionally used for joint pain and urinary complaints.",
    uses: "Allergy tea, Nourishing infusions",
    properties: "May help reduce inflammation, May increase urination, Nourishing",
    cautions: "The fresh plant stings the skin; cook or dry it before use.",
    imageUrl: "/herbs/nettle.jpg",
  },
  {
    name: "Cilantro",
    scientificName: "Coriandrum sativum",
    category: "Culinary",
    summary: "A fresh, citrusy kitchen herb. Its seeds, sold as coriander, are traditionally used to support digestion.",
    uses: "Salsas, Curries, Garnish",
    properties: "Antioxidant, Mild digestive aid",
    cautions: "Some people find it tastes soapy because of their genes.",
    imageUrl: "/herbs/cilantro.jpg",
  },
  {
    name: "St. John's Wort",
    scientificName: "Hypericum perforatum",
    category: "Medicinal",
    summary: "A yellow-flowered herb traditionally used to support mood. It interacts with many common medicines.",
    uses: "Low mood, Wound salves (on the skin)",
    properties: "Antidepressant-like, May help reduce inflammation",
    cautions: "Interacts with many medicines, including antidepressants and birth control pills.",
    imageUrl: "/herbs/st-johns-wort.jpg",
  },
  {
    name: "Fennel",
    scientificName: "Foeniculum vulgare",
    category: "Culinary",
    summary: "An anise-flavored plant whose seeds and bulb are both widely eaten. The seeds are traditionally used for digestion.",
    uses: "Digestive tea, Salads, Roasted bulb dishes",
    properties: "May relieve gas, Mild estrogen-like effects, May ease cramps",
    cautions: "Avoid concentrated forms during pregnancy.",
    imageUrl: "/herbs/fennel.jpg",
  },
  {
    name: "Ashwagandha",
    scientificName: "Withania somnifera",
    category: "Medicinal",
    summary: "A root from Ayurvedic medicine, traditionally used to help the body cope with stress.",
    uses: "Stress, Sleep, Energy",
    properties: "Adaptogen, Calming, May help reduce inflammation",
    cautions: "Avoid during pregnancy and with certain thyroid or autoimmune conditions.",
    imageUrl: "/herbs/ashwagandha.jpg",
  },
  {
    name: "Parsley",
    scientificName: "Petroselinum crispum",
    category: "Culinary",
    summary: "A versatile, mild kitchen herb used as both a garnish and a flavor base.",
    uses: "Garnish, Tabbouleh, Stocks and sauces",
    properties: "May increase urination, Rich in vitamins K and C",
    cautions: "Avoid medicinal doses (not cooking amounts) during pregnancy.",
    imageUrl: "/herbs/parsley.jpg",
  },
  {
    name: "Garlic",
    scientificName: "Allium sativum",
    category: "Culinary",
    summary: "A pungent kitchen bulb traditionally used for heart and circulation health. Research suggests garlic supplements may lower blood pressure and cholesterol a little.",
    uses: "Cooking, High blood pressure, Cholesterol, Colds",
    properties: "May lower blood pressure slightly, May lower cholesterol slightly",
    cautions: "Garlic supplements may raise bleeding risk; stop 7 days before surgery and check with a doctor if you take blood thinners.",
    imageUrl: "/herbs/garlic.jpg",
  },
  {
    name: "Hawthorn",
    scientificName: "Crataegus monogyna",
    category: "Medicinal",
    summary: "A flowering shrub of the rose family, traditionally used for the heart. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Heart health, Circulation, Stress",
    properties: "Heart support (traditional), Calming",
    cautions: "Heart symptoms need a doctor's diagnosis first; may interact with heart medicines.",
    imageUrl: "/herbs/hawthorn.jpg",
  },
  {
    name: "Ginseng",
    scientificName: "Panax ginseng",
    category: "Medicinal",
    summary: "A root long used in traditional Chinese medicine as a calming herb and an adaptogen. Research on its effects is mixed.",
    uses: "Energy, Thinking and focus, Blood sugar",
    properties: "Adaptogen, Calming",
    cautions: "May lower blood sugar and affect blood clotting; not for children or during pregnancy or breastfeeding.",
    imageUrl: "/herbs/ginseng.jpg",
  },
  {
    name: "Ginkgo",
    scientificName: "Ginkgo biloba",
    category: "Medicinal",
    summary: "Leaves of the ginkgo tree, sometimes called the fossil tree, traditionally used in Europe for minor circulation problems and in Chinese medicine for cough.",
    uses: "Circulation, Cold hands and feet, Memory",
    properties: "Circulation support, Memory support",
    cautions: "May increase bleeding risk, especially with blood thinners; fresh seeds are poisonous.",
    imageUrl: "/herbs/ginkgo.jpg",
  },
  {
    name: "Gynostemma",
    scientificName: "Gynostemma pentaphyllum",
    category: "Medicinal",
    summary: "A plant from the cucumber family, known in China as jiaogulan and used in traditional medicine and teas. It has been studied for lowering cholesterol.",
    uses: "Tea, Cholesterol",
    properties: "May lower cholesterol",
    cautions: "Research on its safety is limited, though no serious side effects were reported in trials.",
    imageUrl: "/herbs/gynostemma.jpg",
  },
  {
    name: "Reishi",
    scientificName: "Ganoderma lucidum",
    category: "Medicinal",
    summary: "A mushroom prized for centuries in traditional Chinese, Japanese and Korean medicine. A Cochrane review found it didn't lower heart disease risk factors.",
    uses: "Energy, Immune support, Heart health",
    properties: "Immune support",
    cautions: "Liver damage has been reported; may raise bleeding risk with blood thinners.",
    imageUrl: "/herbs/reishi.jpg",
  },
  {
    name: "Motherwort",
    scientificName: "Leonurus cardiaca",
    category: "Medicinal",
    summary: "A plant from the mint family, traditionally used as a heart tonic and for women's health. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Nervous tension, Women's health",
    properties: "Calming, Heart tonic",
    cautions: "Must not be taken during pregnancy; may increase bleeding risk with blood thinners.",
    imageUrl: "/herbs/motherwort.jpg",
  },
  {
    name: "Linden",
    scientificName: "Tilia cordata",
    category: "Medicinal",
    summary: "Flowers of the lime (linden) tree, traditionally made into tea for colds, stress and nervous heart complaints.",
    uses: "Tea, Colds, Stress, Palpitations",
    properties: "Calming",
    cautions: "Some sources advise people with heart conditions to avoid it; not recommended during pregnancy.",
    imageUrl: "/herbs/linden.jpg",
  },
  {
    name: "Hibiscus",
    scientificName: "Hibiscus sabdariffa",
    category: "Medicinal",
    summary: "The tart red calyces of this flower are made into a tea known as roselle or sour tea. Reviews of trials suggest it may lower blood pressure.",
    uses: "Tea, High blood pressure, Cholesterol",
    properties: "May lower blood pressure, Antioxidant",
    cautions: "How it interacts with blood pressure medicines and water pills hasn't been fully studied; check with your doctor.",
    imageUrl: "/herbs/hibiscus.jpg",
  },
  {
    name: "Flaxseed",
    scientificName: "Linum usitatissimum",
    category: "Culinary",
    summary: "Small seeds rich in fiber and the omega-3 fat ALA, eaten whole, ground or as oil. Research suggests flaxseed may lower blood pressure and cholesterol slightly.",
    uses: "Food, Constipation, Blood pressure, Cholesterol",
    properties: "Gentle laxative, May lower cholesterol slightly",
    cautions: "Don't eat raw or unripe seeds; not for people with swallowing problems or a blocked gut.",
    imageUrl: "/herbs/flaxseed.jpg",
  },
  {
    name: "Cinnamon",
    scientificName: "Cinnamomum verum",
    category: "Culinary",
    summary: "A warm kitchen spice made from tree bark, traditionally used for digestive complaints. Research on its effects on blood sugar and cholesterol is mixed.",
    uses: "Baking and cooking, Digestion, Blood sugar",
    properties: "May relieve gas and bloating",
    cautions: "Cassia cinnamon contains coumarin, which has been linked to liver problems; avoid large amounts during pregnancy.",
    imageUrl: "/herbs/cinnamon.jpg",
  },
  {
    name: "Cerasee",
    scientificName: "Momordica charantia",
    category: "Medicinal",
    summary: "A bitter plant known in Jamaica as cerasee and elsewhere as bitter melon, widely used as a folk remedy for diabetes and high blood pressure.",
    uses: "Blood sugar, High blood pressure",
    properties: "May lower blood sugar",
    cautions: "May add to the effects of diabetes medicines; avoid during pregnancy.",
    imageUrl: "/herbs/cerasee.jpg",
  },
  {
    name: "Red Clover",
    scientificName: "Trifolium pratense",
    category: "Medicinal",
    summary: "A pink-flowered clover traditionally used for skin problems and whooping cough. It has been studied for menopausal hot flashes, with inconsistent results.",
    uses: "Menopause, Skin care",
    properties: "Plant estrogens (isoflavones)",
    cautions: "May increase bleeding risk; avoid with hormone-sensitive cancers, blood thinners, or during pregnancy.",
    imageUrl: "/herbs/red-clover.jpg",
  },
  {
    name: "Raspberry Leaf",
    scientificName: "Rubus idaeus",
    category: "Medicinal",
    summary: "Leaves of the raspberry plant, made into tea. Traditionally used for period cramps and widely used in pregnancy, though its safety in pregnancy hasn't been proven.",
    uses: "Tea, Period cramps, Pregnancy (traditional)",
    properties: "May ease period cramps",
    cautions: "Not proven safe in pregnancy; ask your midwife or doctor first.",
    imageUrl: "/herbs/raspberry-leaf.jpg",
  },
  {
    name: "Chasteberry",
    scientificName: "Vitex agnus-castus",
    category: "Medicinal",
    summary: "The berries of the chaste tree (vitex), recognized in Europe for easing PMS (premenstrual syndrome).",
    uses: "PMS, Breast tenderness, Women's health",
    properties: "May ease PMS",
    cautions: "Not for use during pregnancy or breastfeeding, or with hormone-sensitive cancers.",
    imageUrl: "/herbs/chasteberry.jpg",
  },
  {
    name: "Black Cohosh",
    scientificName: "Actaea racemosa",
    category: "Medicinal",
    summary: "A root used traditionally by Native Americans and recognized in Europe for menopausal hot flushes. Rare liver problems have been reported.",
    uses: "Menopause, Hot flashes",
    properties: "May ease hot flashes",
    cautions: "Stop and see a doctor if you notice dark urine, yellow skin or eyes, or unusual tiredness.",
    imageUrl: "/herbs/black-cohosh.jpg",
  },
  {
    name: "Dong Quai",
    scientificName: "Angelica sinensis",
    category: "Medicinal",
    summary: "A root that is one of the most widely used herbs in traditional Chinese medicine for women's health, including period pain and menopause.",
    uses: "Period pain, Menopause, Women's health",
    properties: "Women's tonic (traditional)",
    cautions: "May increase bleeding with blood thinners; avoid during pregnancy and breastfeeding.",
    imageUrl: "/herbs/dong-quai.jpg",
  },
  {
    name: "Shatavari",
    scientificName: "Asparagus racemosus",
    category: "Medicinal",
    summary: "A root used in Ayurveda as a tonic and to increase breast milk. Research on it is limited.",
    uses: "Breast milk, Menopause, Women's health",
    properties: "Tonic, May increase breast milk (traditional)",
    cautions: "Its safety in pregnancy is uncertain; ask your doctor or midwife first.",
    imageUrl: "/herbs/shatavari.jpg",
  },
  {
    name: "Queen Anne's Lace",
    scientificName: "Daucus carota",
    category: "Medicinal",
    summary: "Wild carrot, whose seeds have long been used in folk medicine to prevent pregnancy. It hasn't been proven safe or effective, and it looks like deadly poison hemlock.",
    uses: "Traditional birth control, Urinary complaints",
    properties: "Traditionally used to prevent pregnancy",
    cautions: "Not reliable birth control; avoid if pregnant or trying to conceive; easily confused with poison hemlock.",
    imageUrl: "/herbs/queen-annes-lace.jpg",
  },
  {
    name: "Maca",
    scientificName: "Lepidium meyenii",
    category: "Medicinal",
    summary: "A root vegetable from the high Andes of Peru, used for centuries as food and to boost energy and fertility. Its effects haven't been proven in rigorous trials.",
    uses: "Energy, Fertility, Sexual health, Menopause",
    properties: "Adaptogen",
    cautions: "Avoid during pregnancy and breastfeeding; may affect testosterone blood tests.",
    imageUrl: "/herbs/maca.jpg",
  },
  {
    name: "Milk Thistle",
    scientificName: "Silybum marianum",
    category: "Medicinal",
    summary: "A tall, purple-flowered thistle from Europe, long used for liver problems. Studies of it and its extract silymarin in liver disease have been conflicting or too limited to show a clear benefit.",
    uses: "Liver support, Indigestion, Breast milk",
    properties: "Traditionally used to support the liver",
    cautions: "May cause allergic reactions in people allergic to ragweed, daisies or related plants.",
    imageUrl: "/herbs/milk-thistle.jpg",
  },
  {
    name: "Dandelion",
    scientificName: "Taraxacum officinale",
    category: "Medicinal",
    summary: "A plant whose root and leaves have long been used for indigestion and, historically, for problems with bile flow. There is very little research on it in people.",
    uses: "Indigestion, Bile flow, Liver and gallbladder (traditional), Appetite, Urinary complaints",
    properties: "May increase urination",
    cautions: "Don't use dandelion medicines if you have gallstones, a blocked bile duct or liver disease.",
    imageUrl: "/herbs/dandelion.jpg",
  },
  {
    name: "Artichoke Leaf",
    scientificName: "Cynara cardunculus",
    category: "Medicinal",
    summary: "Leaves of the artichoke plant, recognized in Europe for indigestion, fullness and bloating. Several small trials suggest it may lower liver enzyme levels in fatty liver disease.",
    uses: "Indigestion, Bloating, Fatty liver",
    properties: "May ease indigestion",
    cautions: "Don't use it if you have gallstones, a blocked bile duct or liver disease, or are allergic to daisy-family plants.",
    imageUrl: "/herbs/artichoke.jpg",
  },
  {
    name: "Chanca Piedra",
    scientificName: "Phyllanthus niruri",
    category: "Medicinal",
    summary: "A plant traditionally used in Malay, Chinese and Ayurvedic medicine for kidney stones and liver problems. It has been studied for both, with mixed results.",
    uses: "Kidney stones, Liver problems, Jaundice, Indigestion",
    properties: "Traditionally used for the liver and kidneys",
    cautions: "Kidney stones and liver disease need medical care; don't use it in place of treatment.",
    imageUrl: "/herbs/chanca-piedra.jpg",
  },
  {
    name: "Burdock",
    scientificName: "Arctium lappa",
    category: "Medicinal",
    summary: "A plant whose root has been eaten as food in Asia for centuries. It is traditionally used as a \"blood purifier\" and for skin problems, but there is little evidence in people.",
    uses: "Skin problems, Appetite, Urinary complaints, Blood purifier (traditional)",
    properties: "Traditionally used as a blood purifier",
    cautions: "Avoid during pregnancy; can cause severe allergic reactions, and one case of liver injury has been reported.",
    imageUrl: "/herbs/burdock.jpg",
  },
  {
    name: "Schisandra",
    scientificName: "Schisandra chinensis",
    category: "Medicinal",
    summary: "A fruit known in Chinese as wu wei zi (\"five-flavor fruit\"), long used in traditional Chinese medicine for the liver, coughs and energy. Studies in people are few and small.",
    uses: "Liver problems, Cough, Energy, Tonic",
    properties: "Tonic, Adaptogen",
    cautions: "Can change blood levels of some medicines, including tacrolimus; it can also lower liver test results.",
    imageUrl: "/herbs/schisandra.jpg",
  },
  {
    name: "Turkey Tail",
    scientificName: "Trametes versicolor",
    category: "Medicinal",
    summary: "A mushroom used in traditional Chinese medicine as a tonic. Extracts from it are used alongside cancer treatment in Japan and China.",
    uses: "Immune support, General health, Cancer care (alongside treatment)",
    properties: "Immune support",
    cautions: "Its safety in pregnancy and breastfeeding isn't known; talk to your doctor before using supplements.",
    imageUrl: "/herbs/turkey-tail.jpg",
  },
  {
    name: "Green Tea",
    scientificName: "Camellia sinensis",
    category: "Medicinal",
    summary: "Unfermented leaves of the tea plant, drunk for thousands of years. Drinking the tea is considered safe, but concentrated green tea extract supplements have rarely caused serious liver damage.",
    uses: "Tea, Weight, Cholesterol, Fatty liver",
    properties: "Antioxidant",
    cautions: "Green tea extract pills have rarely caused severe liver damage; contains caffeine.",
    imageUrl: "/herbs/green-tea.jpg",
  },
  {
    name: "Gold Coin Grass",
    scientificName: "Lysimachia christinae, Desmodium styracifolium",
    category: "Medicinal",
    summary: "A name used in traditional Chinese medicine for two plants, Lysimachia christinae (jin qian cao) and Desmodium styracifolium (guang jin qian cao). Both are used for gallstones and urinary stones; a large trial found a Desmodium extract helped small stones pass.",
    uses: "Gallstones, Kidney stones, Bile flow, Urinary complaints, Jaundice",
    properties: "Traditionally used for gallstones and kidney stones",
    cautions: "These are different plants, and research on one may not apply to the other. Gallstones and kidney stones need medical care.",
    imageUrl: "/herbs/gold-coin-grass.jpg",
  },
  {
    name: "Calendula",
    scientificName: "Calendula officinalis",
    category: "Medicinal",
    summary: "The pot marigold, used in creams and ointments to soothe the skin. It is recognized in Europe for minor skin inflammation such as sunburn and to help minor wounds heal.",
    uses: "Minor wounds, Sunburn, Skin inflammation, Mouth and throat inflammation",
    properties: "May help minor wounds heal",
    cautions: "Can cause skin allergies; don't use it if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/calendula.jpg",
  },
  {
    name: "Horsetail",
    scientificName: "Equisetum arvense",
    category: "Medicinal",
    summary: "A plant recognized in Europe as a traditional medicine for minor urinary complaints and, as a wash or dressing, for superficial wounds. One small trial found a horsetail ointment helped episiotomy wounds heal.",
    uses: "Superficial wounds, Urinary complaints",
    properties: "May increase urination",
    cautions: "Don't use it for urinary complaints if you've been told to limit fluids, for example with serious heart or kidney disease.",
    imageUrl: "/herbs/horsetail.jpg",
  },
  {
    name: "Alfalfa",
    scientificName: "Medicago sativa",
    category: "Medicinal",
    summary: "A widely used food and animal-feed crop, promoted as a supplement for many uses, including lowering cholesterol. Extracts have been studied on skin cells in the lab, but not on skin in people.",
    uses: "Cholesterol, Skin care (lab research), Nutrition",
    properties: "Antioxidant",
    cautions: "Avoid if you have lupus, gout, or are pregnant or breastfeeding; raw sprouts have caused food poisoning.",
    imageUrl: "/herbs/alfalfa.jpg",
  },
  {
    name: "Rosehips",
    scientificName: "Rosa canina",
    category: "Medicinal",
    summary: "The fruit of wild roses such as the dog rose, rich in vitamin C. Rosehip seed oil and powder have been studied for scars and wrinkles in small trials.",
    uses: "Scars, Wrinkles, Skin care, Vitamin C",
    properties: "Antioxidant",
    cautions: "Research on skin use is limited to small studies.",
    imageUrl: "/herbs/rosehips.jpg",
  },
  {
    name: "English Plantain",
    scientificName: "Plantago lanceolata",
    category: "Medicinal",
    summary: "A plant (also called ribwort plantain) whose leaves are recognized in Europe as a traditional medicine for coughs, sore throats and minor skin inflammation.",
    uses: "Skin inflammation, Cough, Sore throat",
    properties: "Soothing (traditional)",
    cautions: "Don't use it if you're allergic to plantain or its pollen.",
    imageUrl: "/herbs/english-plantain.jpg",
  },
  {
    name: "Snakeroot",
    scientificName: "Ageratina pichinchensis",
    category: "Medicinal",
    summary: "A plant native to Mexico, known there as axihuitl, long used in traditional Mexican medicine for skin problems and wounds. Small trials in Mexico have tested extracts for fungal skin and nail infections and leg ulcers.",
    uses: "Fungal skin infections, Nail fungus, Wounds, Skin ulcers",
    properties: "Antifungal",
    cautions: "Other plants are also called snakeroot (for example black cohosh); this page is only about Ageratina pichinchensis.",
    imageUrl: "/herbs/snakeroot.jpg",
  },
  {
    name: "Mugwort",
    scientificName: "Artemisia vulgaris",
    category: "Medicinal",
    summary: "A common plant called the \"mother of herbs\" in the Middle Ages, when it was used on wounds. It is also used in Chinese moxibustion. Mugwort is a major cause of pollen allergy and can cause skin allergies.",
    uses: "Wounds (traditional), Digestion, Moxibustion, Menstrual complaints (traditional)",
    properties: "Bitter, Aromatic",
    cautions: "Avoid during pregnancy (large amounts may cause miscarriage) and if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/mugwort.jpg",
  },
  {
    name: "Neem",
    scientificName: "Azadirachta indica",
    category: "Medicinal",
    summary: "A South Asian tree used in Ayurvedic medicine on the skin and for oral hygiene. Neem works against lice, and a small trial found a neem lotion worked as well as standard treatment for scabies.",
    uses: "Skin conditions, Lice, Scabies, Oral hygiene",
    properties: "Kills lice and pests",
    cautions: "Never swallow neem oil: it has caused severe poisoning in children and adults.",
    imageUrl: "/herbs/neem.jpg",
  },
  {
    name: "Andrographis",
    scientificName: "Andrographis paniculata",
    category: "Medicinal",
    summary: "A bitter herb used across Asia for infections and fevers, and traditionally for skin inflammation and wounds. It has mainly been studied for colds and flu.",
    uses: "Colds and flu, Skin inflammation (traditional), Wounds (traditional)",
    properties: "Bitter tonic",
    cautions: "Can cause allergic reactions and skin rash, and may interact with many medicines.",
    imageUrl: "/herbs/andrographis.jpg",
  },
  {
    name: "Chickweed",
    scientificName: "Stellaria media",
    category: "Medicinal",
    summary: "A wild weed found worldwide, eaten as a leafy green and traditionally used for skin problems such as burns, cuts and scratches. It hasn't been studied in people.",
    uses: "Burns, Cuts, Skin ailments, Food",
    properties: "Soothing (traditional)",
    cautions: "No studies in people have tested its safety or effects.",
    imageUrl: "/herbs/chickweed.jpg",
  },
  {
    name: "Goldenseal",
    scientificName: "Hydrastis canadensis",
    category: "Medicinal",
    summary: "A North American plant with a bright yellow root, used by Native Americans on wounds and for skin and eye conditions. There isn't enough research to know whether it helps any health condition.",
    uses: "Wounds (traditional), Skin and eye irritation (traditional), Colds, Digestion",
    properties: "Bitter tonic",
    cautions: "Affects many medicines, including metformin; don't use in pregnancy, breastfeeding or babies.",
    imageUrl: "/herbs/goldenseal.jpg",
  },
  {
    name: "Passion Flower",
    scientificName: "Passiflora incarnata",
    category: "Medicinal",
    summary: "A climbing vine from the Americas, used as a calming herb since at least the 1500s. It is recognized in Europe for mild stress and to help sleep, and small studies suggest it may ease anxiety.",
    uses: "Sleep, Anxiety, Stress, Calming tea",
    properties: "May make you feel sleepy or relaxed",
    cautions: "Can cause drowsiness; avoid in pregnancy and for 2 weeks before surgery.",
    imageUrl: "/herbs/passion-flower.jpg",
  },
  {
    name: "Holy Basil",
    scientificName: "Ocimum tenuiflorum",
    category: "Medicinal",
    summary: "Tulsi, a highly revered plant in India used in Ayurveda for stress, coughs, asthma and many other conditions. Small studies suggest it may ease stress and anxiety.",
    uses: "Stress, Anxiety, Cough, Asthma (traditional), Memory",
    properties: "Adaptogen",
    cautions: "Most studies were small and done in India; long-term safety isn't well studied.",
    imageUrl: "/herbs/holy-basil.jpg",
  },
  {
    name: "Catnip",
    scientificName: "Nepeta cataria",
    category: "Medicinal",
    summary: "A plant in the mint family traditionally used for colic, coughs, asthma and nervous upset. Its oil is also an effective mosquito repellent.",
    uses: "Colic, Cough, Asthma (traditional), Nervous upset (traditional), Mosquito repellent",
    properties: "May ease cramps",
    cautions: "A toddler became very drowsy after eating a large amount; keep away from children.",
    imageUrl: "/herbs/catnip.jpg",
  },
  {
    name: "Lion's Mane",
    scientificName: "Hericium erinaceus",
    category: "Medicinal",
    summary: "An edible mushroom studied for memory and mood. Small trials suggest it may help thinking in older adults with mild memory problems.",
    uses: "Memory, Focus, Mood, Sleep",
    properties: "Brain support (under study)",
    cautions: "May cause stomach upset, headache or allergic reactions; research is limited.",
    imageUrl: "/herbs/lions-mane.jpg",
  },
  {
    name: "Gotu Kola",
    scientificName: "Centella asiatica",
    category: "Medicinal",
    summary: "A plant used in traditional medicine for circulation, wounds and memory. Small studies suggest possible benefits for anxiety and thinking, but the evidence isn't strong.",
    uses: "Memory, Anxiety, Circulation, Wounds",
    properties: "May help wounds heal",
    cautions: "Liver damage and skin rashes have been reported; not the same as caffeine-containing kola nut.",
    imageUrl: "/herbs/gotu-kola.jpg",
  },
  {
    name: "Siamese Cassia",
    scientificName: "Senna siamea",
    category: "Medicinal",
    summary: "A tree whose leaves are eaten in Thailand, where it is called khi lek and traditionally used for sleep. A calming product made from it caused cases of hepatitis.",
    uses: "Sleep (traditional), Anxiety (traditional), Fever, Food",
    properties: "May make you feel sleepy (in animals)",
    cautions: "Barakol, its calming compound, has caused liver inflammation (hepatitis).",
    imageUrl: "/herbs/siamese-cassia.jpg",
  },
  {
    name: "Brahmi",
    scientificName: "Bacopa monnieri",
    category: "Medicinal",
    summary: "Bacopa, long used in Ayurvedic medicine for nerve and behavior problems. Reviews of trials suggest it may modestly improve memory and attention speed.",
    uses: "Memory, Attention, Learning",
    properties: "Brain tonic (traditional)",
    cautions: "Research on its safety is limited; talk to your doctor before using it.",
    imageUrl: "/herbs/brahmi.jpg",
  },
  {
    name: "Kava",
    scientificName: "Piper methysticum",
    category: "Medicinal",
    summary: "A root from the South Pacific, drunk in ceremonies for thousands of years. It may ease anxiety short term, but it has been linked to rare, sometimes fatal, liver damage.",
    uses: "Anxiety, Relaxation, Ceremonial drink",
    properties: "May ease anxiety",
    cautions: "Linked to serious liver damage; don't combine with alcohol or sleep and anxiety medicines.",
    imageUrl: "/herbs/kava.jpg",
  },
  {
    name: "Mullein",
    scientificName: "Verbascum thapsus",
    category: "Medicinal",
    summary: "A plant whose flowers are made into tea and recognized in Europe as a traditional medicine for sore throat with a dry cough and cold.",
    uses: "Sore throat, Dry cough, Colds, Tea",
    properties: "Soothing (traditional)",
    cautions: "Not recommended for children under 12 or during pregnancy and breastfeeding.",
    imageUrl: "/herbs/mullein.jpg",
  },
  {
    name: "Elecampane",
    scientificName: "Inula helenium",
    category: "Medicinal",
    summary: "A root used for centuries in European medicine, including medieval Ireland, for coughs, bronchitis and other chest complaints. Germany's Commission E didn't approve it, citing weak evidence and possible side effects.",
    uses: "Cough, Bronchitis, Chest congestion",
    properties: "May help loosen mucus (traditional)",
    cautions: "Not officially approved as a medicine because of weak evidence and possible side effects; may cause skin allergies.",
    imageUrl: "/herbs/elecampane.jpg",
  },
  {
    name: "Eucalyptus",
    scientificName: "Eucalyptus globulus",
    category: "Medicinal",
    summary: "Leaves of the eucalyptus tree, taken as tea or inhaled in steam, and recognized in Europe as a traditional medicine for cough with a cold.",
    uses: "Cough, Colds, Steam inhalation, Tea",
    properties: "May help loosen mucus (traditional)",
    cautions: "Never use it in children under 30 months: it can cause a dangerous tightening of the vocal cords.",
    imageUrl: "/herbs/eucalyptus.jpg",
  },
  {
    name: "Licorice",
    scientificName: "Glycyrrhiza glabra",
    category: "Medicinal",
    summary: "A root used since ancient times in Egyptian, Greek, Chinese and Indian medicine for coughs, asthma and wounds. Recognized in Europe for cough with a cold and for indigestion, but too much can raise blood pressure and upset heart rhythm.",
    uses: "Cough, Sore throat, Indigestion, Heartburn",
    properties: "May help loosen mucus",
    cautions: "Large amounts or long-term use can cause high blood pressure, low potassium and dangerous heart rhythms.",
    imageUrl: "/herbs/licorice.jpg",
  },
  {
    name: "Eyebright",
    scientificName: "Euphrasia officinalis",
    category: "Medicinal",
    summary: "A plant traditionally used on the eyes and in nasal ointments for colds. European regulators declined to approve it because its benefits aren't documented and home-made eye washes aren't safe.",
    uses: "Eye irritation (traditional), Nasal irritation with colds (traditional)",
    properties: "Traditionally used for eye irritation",
    cautions: "Don't put home-made eyebright preparations in your eyes: they aren't hygienic or safe.",
    imageUrl: "/herbs/eyebright.jpg",
  },
  {
    name: "Grindelia",
    scientificName: "Grindelia robusta",
    category: "Medicinal",
    summary: "Gumweed, a daisy-family plant whose above-ground parts are recognized in Europe as a traditional medicine for cough with a cold in adults.",
    uses: "Cough, Colds",
    properties: "Traditionally used for cough",
    cautions: "For adults only; avoid if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/grindelia.jpg",
  },
  {
    name: "Horehound",
    scientificName: "Marrubium vulgare",
    category: "Medicinal",
    summary: "White horehound, a bitter mint-family herb recognized in Europe as a traditional medicine to help bring up phlegm with a cold, and for indigestion and poor appetite.",
    uses: "Cough, Chest congestion, Indigestion, Appetite",
    properties: "May help loosen mucus, Bitter",
    cautions: "Don't use it with liver disease, a blocked bile duct or a bowel blockage; ask a doctor first if you have gallstones or an ulcer.",
    imageUrl: "/herbs/horehound.jpg",
  },
  {
    name: "Osha",
    scientificName: "Ligusticum porteri",
    category: "Medicinal",
    summary: "A root from the Rocky Mountains, long used by Hispanic and Native American peoples for colds, flu and chest infections. It has only been studied in the lab.",
    uses: "Colds, Flu, Chest infections, Indigestion",
    properties: "Traditionally used for colds and flu",
    cautions: "No studies in people have tested its safety or effects.",
    imageUrl: "/herbs/osha.jpg",
  },
  {
    name: "Yerba Santa",
    scientificName: "Eriodictyon californicum",
    category: "Medicinal",
    summary: "A shrub from the southwestern United States and northern Mexico whose leaves have been used by Indigenous peoples for centuries, especially for breathing problems.",
    uses: "Breathing problems (traditional), Cough",
    properties: "Traditionally used for breathing problems",
    cautions: "It hasn't been studied in people for any health use.",
    imageUrl: "/herbs/yerba-santa.jpg",
  },
  {
    name: "Wild Cherry",
    scientificName: "Prunus serotina",
    category: "Medicinal",
    summary: "Black cherry (capulín), a North American tree used in Mexican folk medicine for cough, high blood pressure and digestive problems. Its seeds and leaves contain compounds that can release cyanide.",
    uses: "Cough (traditional), Digestion (traditional)",
    properties: "Traditionally used for cough",
    cautions: "Seeds and leaves contain compounds that release cyanide when crushed.",
    imageUrl: "/herbs/wild-cherry.jpg",
  },
  {
    name: "Pleurisy Root",
    scientificName: "Asclepias tuberosa",
    category: "Medicinal",
    summary: "A milkweed whose root was traditionally used for breathing problems and to loosen mucus. It contains heart-affecting compounds, and its sap has injured people's eyes.",
    uses: "Breathing problems (traditional), Chest congestion (traditional)",
    properties: "Contains heart-affecting compounds (cardiac glycosides)",
    cautions: "Contains cardiac glycosides; its sap can seriously irritate the eyes.",
    imageUrl: "/herbs/pleurisy-root.jpg",
  },
];

async function main() {
  for (const herb of herbs) {
    await prisma.herb.upsert({
      where: { name: herb.name },
      update: herb,
      create: herb,
    });
  }
  console.log(`Seeded ${herbs.length} herbs.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
