import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter });

const herbs = [
  {
    name: "Basil",
    scientificName: "Ocimum basilicum",
    category: "Culinary",
    summary: "A fragrant, warm-weather kitchen herb central to Italian and Southeast Asian cooking.",
    uses: "Pesto, Tomato dishes, Teas, Aromatherapy",
    properties: "May help reduce inflammation, Antioxidant, May fight bacteria",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/basil.jpg",
  },
  {
    name: "Chamomile",
    scientificName: "Matricaria chamomilla",
    category: "Medicinal",
    summary: "A daisy-like flower, usually made into tea, traditionally used for relaxation and digestive comfort.",
    uses: "Sleep, Calming tea, Soothing skin",
    properties: "Mildly relaxing, May help reduce inflammation, May ease cramps",
    cautions: "May cause an allergic reaction in people allergic to ragweed.",
    imageUrl: "/herbs/chamomile.jpg",
  },
  {
    name: "Peppermint",
    scientificName: "Mentha piperita",
    category: "Medicinal",
    summary: "A cooling, menthol-rich herb traditionally used for digestion and headaches. Research suggests peppermint oil may help IBS symptoms.",
    uses: "Digestive tea, Headaches, Aromatherapy",
    properties: "May ease cramps, May relieve pain, May relieve gas",
    cautions: "Can make acid reflux worse in some people.",
    imageUrl: "/herbs/peppermint.jpg",
  },
  {
    name: "Rosemary",
    scientificName: "Salvia rosmarinus",
    category: "Culinary",
    summary: "A woody, pine-scented kitchen herb popular in roasted dishes and hair care.",
    uses: "Roasted meats and vegetables, Hair rinses, Memory",
    properties: "Antioxidant, May fight germs, May boost circulation",
    cautions: "High doses may cause contractions of the womb; avoid during pregnancy.",
    imageUrl: "/herbs/rosemary.jpg",
  },
  {
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    category: "Aromatic",
    summary: "A purple-flowered herb prized for its scent and traditionally used to relax.",
    uses: "Aromatherapy, Sleep, Skin care",
    properties: "May ease anxiety, Calming, May fight germs",
    cautions: "Don't swallow the essential oil undiluted.",
    imageUrl: "/herbs/lavender.jpg",
  },
  {
    name: "Ginger",
    scientificName: "Zingiber officinale",
    category: "Medicinal",
    summary: "A spicy, warming root traditionally used for nausea and inflammation. Research suggests it may help with nausea during pregnancy.",
    uses: "Nausea, Teas, Cooking, Inflammation",
    properties: "May ease nausea, May help reduce inflammation, Aids digestion",
    cautions: "May interact with blood-thinning medicines at high doses.",
    imageUrl: "/herbs/ginger.jpg",
  },
  {
    name: "Echinacea",
    scientificName: "Echinacea purpurea",
    category: "Medicinal",
    summary: "A purple coneflower traditionally used to support the immune system, especially for colds.",
    uses: "Colds and flu, Tinctures, Teas",
    properties: "May stimulate the immune system, May help reduce inflammation",
    cautions: "Not recommended for people with autoimmune conditions without medical advice.",
    imageUrl: "/herbs/echinacea.jpg",
  },
  {
    name: "Thyme",
    scientificName: "Thymus vulgaris",
    category: "Culinary",
    summary: "A small-leaved, earthy herb used widely in savory cooking and traditionally in cough remedies.",
    uses: "Soups and stews, Coughs, Germ-fighting gargle",
    properties: "May fight germs, May loosen mucus, May ease cramps",
    cautions: "The essential oil is strong; use it diluted.",
    imageUrl: "/herbs/thyme.jpg",
  },
  {
    name: "Sage",
    scientificName: "Salvia officinalis",
    category: "Culinary",
    summary: "A silvery-leaved kitchen herb with a savory, slightly peppery flavor, traditionally used for sore throats and indigestion.",
    uses: "Stuffing and sausages, Sore throat gargle, Memory",
    properties: "Antioxidant, May fight germs, Astringent (tightens tissues)",
    cautions: "Avoid large medicinal doses during pregnancy.",
    imageUrl: "/herbs/sage.jpg",
  },
  {
    name: "Turmeric",
    scientificName: "Curcuma longa",
    category: "Medicinal",
    summary: "A golden root used in curries, known for its natural compound curcumin and traditionally used for inflammation.",
    uses: "Curries, Golden milk, Joints",
    properties: "May help reduce inflammation, Antioxidant",
    cautions: "May interact with blood thinners; high doses can upset the stomach.",
    imageUrl: "/herbs/turmeric.jpg",
  },
  {
    name: "Lemon Balm",
    scientificName: "Melissa officinalis",
    category: "Medicinal",
    summary: "A lemon-scented relative of mint, traditionally used to ease stress and help with sleep.",
    uses: "Calming tea, Stress, Cold sores (on the skin)",
    properties: "Mildly relaxing, May fight viruses, May relieve gas",
    cautions: "May interact with thyroid medicines.",
    imageUrl: "/herbs/lemon-balm.jpg",
  },
  {
    name: "Dill",
    scientificName: "Anethum graveolens",
    category: "Culinary",
    summary: "A feathery, tangy kitchen herb often paired with fish and pickles. Its seeds are traditionally used for gas and upset stomach.",
    uses: "Pickling, Fish dishes, Digestive tea",
    properties: "May relieve gas, May ease mild cramps",
    cautions: "Generally safe in cooking amounts.",
    imageUrl: "/herbs/dill.jpg",
  },
  {
    name: "Valerian",
    scientificName: "Valeriana officinalis",
    category: "Medicinal",
    summary: "A root traditionally used to help with sleep.",
    uses: "Sleep, Anxiety",
    properties: "May make you sleepy, May ease anxiety",
    cautions: "Can cause drowsiness; don't combine with alcohol or sedatives.",
    imageUrl: "/herbs/valerian.jpg",
  },
  {
    name: "Oregano",
    scientificName: "Origanum vulgare",
    category: "Culinary",
    summary: "A pungent Mediterranean kitchen herb central to pizza and pasta sauces.",
    uses: "Italian and Greek cooking, Oregano oil",
    properties: "May fight germs, Antioxidant",
    cautions: "Oregano oil is strong and should be diluted.",
    imageUrl: "/herbs/oregano.jpg",
  },
  {
    name: "Nettle",
    scientificName: "Urtica dioica",
    category: "Medicinal",
    summary: "A stinging plant eaten as a spring vegetable and traditionally used for joint pain and urinary complaints.",
    uses: "Allergy tea, Nourishing infusions",
    properties: "May help reduce inflammation, May increase urination, Nourishing",
    cautions: "The fresh plant stings the skin; cook or dry it before use.",
    imageUrl: "/herbs/nettle.jpg",
  },
  {
    name: "Cilantro",
    scientificName: "Coriandrum sativum",
    category: "Culinary",
    summary: "A fresh, citrusy kitchen herb. Its seeds, sold as coriander, are traditionally used to support digestion.",
    uses: "Salsas, Curries, Garnish",
    properties: "Antioxidant, Mild digestive aid",
    cautions: "Some people find it tastes soapy because of their genes.",
    imageUrl: "/herbs/cilantro.jpg",
  },
  {
    name: "St. John's Wort",
    scientificName: "Hypericum perforatum",
    category: "Medicinal",
    summary: "A yellow-flowered herb traditionally used to support mood. It interacts with many common medicines.",
    uses: "Low mood, Wound salves (on the skin)",
    properties: "Antidepressant-like, May help reduce inflammation",
    cautions: "Interacts with many medicines, including antidepressants and birth control pills.",
    imageUrl: "/herbs/st-johns-wort.jpg",
  },
  {
    name: "Fennel",
    scientificName: "Foeniculum vulgare",
    category: "Culinary",
    summary: "An anise-flavored plant whose seeds and bulb are both widely eaten. The seeds are traditionally used for digestion.",
    uses: "Digestive tea, Salads, Roasted bulb dishes",
    properties: "May relieve gas, Mild estrogen-like effects, May ease cramps",
    cautions: "Avoid concentrated forms during pregnancy.",
    imageUrl: "/herbs/fennel.jpg",
  },
  {
    name: "Ashwagandha",
    scientificName: "Withania somnifera",
    category: "Medicinal",
    summary: "A root from Ayurvedic medicine, traditionally used to help the body cope with stress.",
    uses: "Stress, Sleep, Energy",
    properties: "Adaptogen, Calming, May help reduce inflammation",
    cautions: "Avoid during pregnancy and with certain thyroid or autoimmune conditions.",
    imageUrl: "/herbs/ashwagandha.jpg",
  },
  {
    name: "Parsley",
    scientificName: "Petroselinum crispum",
    category: "Culinary",
    summary: "A versatile, mild kitchen herb used as both a garnish and a flavor base.",
    uses: "Garnish, Tabbouleh, Stocks and sauces",
    properties: "May increase urination, Rich in vitamins K and C",
    cautions: "Avoid medicinal doses (not cooking amounts) during pregnancy.",
    imageUrl: "/herbs/parsley.jpg",
  },
  {
    name: "Garlic",
    scientificName: "Allium sativum",
    category: "Culinary",
    summary: "A pungent kitchen bulb traditionally used for heart and circulation health. Research suggests garlic supplements may lower blood pressure and cholesterol a little.",
    uses: "Cooking, High blood pressure, Cholesterol, Colds",
    properties: "May lower blood pressure slightly, May lower cholesterol slightly",
    cautions: "Garlic supplements may raise bleeding risk; stop 7 days before surgery and check with a doctor if you take blood thinners.",
    imageUrl: "/herbs/garlic.jpg",
  },
  {
    name: "Hawthorn",
    scientificName: "Crataegus monogyna",
    category: "Medicinal",
    summary: "A flowering shrub of the rose family, traditionally used for the heart. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Heart health, Circulation, Stress",
    properties: "Heart support (traditional), Calming",
    cautions: "Heart symptoms need a doctor's diagnosis first; may interact with heart medicines.",
    imageUrl: "/herbs/hawthorn.jpg",
  },
  {
    name: "Ginseng",
    scientificName: "Panax ginseng",
    category: "Medicinal",
    summary: "A root long used in traditional Chinese medicine as a calming herb and an adaptogen. Research on its effects is mixed.",
    uses: "Energy, Thinking and focus, Blood sugar",
    properties: "Adaptogen, Calming",
    cautions: "May lower blood sugar and affect blood clotting; not for children or during pregnancy or breastfeeding.",
    imageUrl: "/herbs/ginseng.jpg",
  },
  {
    name: "Ginkgo",
    scientificName: "Ginkgo biloba",
    category: "Medicinal",
    summary: "Leaves of the ginkgo tree, sometimes called the fossil tree, traditionally used in Europe for minor circulation problems and in Chinese medicine for cough.",
    uses: "Circulation, Cold hands and feet, Memory",
    properties: "Circulation support, Memory support",
    cautions: "May increase bleeding risk, especially with blood thinners; fresh seeds are poisonous.",
    imageUrl: "/herbs/ginkgo.jpg",
  },
  {
    name: "Gynostemma",
    scientificName: "Gynostemma pentaphyllum",
    category: "Medicinal",
    summary: "A plant from the cucumber family, known in China as jiaogulan and used in traditional medicine and teas. It has been studied for lowering cholesterol.",
    uses: "Tea, Cholesterol",
    properties: "May lower cholesterol",
    cautions: "Research on its safety is limited, though no serious side effects were reported in trials.",
    imageUrl: "/herbs/gynostemma.jpg",
  },
  {
    name: "Reishi",
    scientificName: "Ganoderma lucidum",
    category: "Medicinal",
    summary: "A mushroom prized for centuries in traditional Chinese, Japanese and Korean medicine. A Cochrane review found it didn't lower heart disease risk factors.",
    uses: "Energy, Immune support, Heart health",
    properties: "Immune support",
    cautions: "Liver damage has been reported; may raise bleeding risk with blood thinners.",
    imageUrl: "/herbs/reishi.jpg",
  },
  {
    name: "Motherwort",
    scientificName: "Leonurus cardiaca",
    category: "Medicinal",
    summary: "A plant from the mint family, traditionally used as a heart tonic and for women's health. Recognized in Europe for nervous heart complaints such as palpitations.",
    uses: "Palpitations, Nervous tension, Women's health",
    properties: "Calming, Heart tonic",
    cautions: "Must not be taken during pregnancy; may increase bleeding risk with blood thinners.",
    imageUrl: "/herbs/motherwort.jpg",
  },
  {
    name: "Linden",
    scientificName: "Tilia cordata",
    category: "Medicinal",
    summary: "Flowers of the lime (linden) tree, traditionally made into tea for colds, stress and nervous heart complaints.",
    uses: "Tea, Colds, Stress, Palpitations",
    properties: "Calming",
    cautions: "Some sources advise people with heart conditions to avoid it; not recommended during pregnancy.",
    imageUrl: "/herbs/linden.jpg",
  },
  {
    name: "Hibiscus",
    scientificName: "Hibiscus sabdariffa",
    category: "Medicinal",
    summary: "The tart red calyces of this flower are made into a tea known as roselle or sour tea. Reviews of trials suggest it may lower blood pressure.",
    uses: "Tea, High blood pressure, Cholesterol",
    properties: "May lower blood pressure, Antioxidant",
    cautions: "How it interacts with blood pressure medicines and water pills hasn't been fully studied; check with your doctor.",
    imageUrl: "/herbs/hibiscus.jpg",
  },
  {
    name: "Flaxseed",
    scientificName: "Linum usitatissimum",
    category: "Culinary",
    summary: "Small seeds rich in fiber and the omega-3 fat ALA, eaten whole, ground or as oil. Research suggests flaxseed may lower blood pressure and cholesterol slightly.",
    uses: "Food, Constipation, Blood pressure, Cholesterol",
    properties: "Gentle laxative, May lower cholesterol slightly",
    cautions: "Don't eat raw or unripe seeds; not for people with swallowing problems or a blocked gut.",
    imageUrl: "/herbs/flaxseed.jpg",
  },
  {
    name: "Cinnamon",
    scientificName: "Cinnamomum verum",
    category: "Culinary",
    summary: "A warm kitchen spice made from tree bark, traditionally used for digestive complaints. Research on its effects on blood sugar and cholesterol is mixed.",
    uses: "Baking and cooking, Digestion, Blood sugar",
    properties: "May relieve gas and bloating",
    cautions: "Cassia cinnamon contains coumarin, which has been linked to liver problems; avoid large amounts during pregnancy.",
    imageUrl: "/herbs/cinnamon.jpg",
  },
  {
    name: "Cerasee",
    scientificName: "Momordica charantia",
    category: "Medicinal",
    summary: "A bitter plant known in Jamaica as cerasee and elsewhere as bitter melon, widely used as a folk remedy for diabetes and high blood pressure.",
    uses: "Blood sugar, High blood pressure",
    properties: "May lower blood sugar",
    cautions: "May add to the effects of diabetes medicines; avoid during pregnancy.",
    imageUrl: "/herbs/cerasee.jpg",
  },
  {
    name: "Red Clover",
    scientificName: "Trifolium pratense",
    category: "Medicinal",
    summary: "A pink-flowered clover traditionally used for skin problems and whooping cough. It has been studied for menopausal hot flashes, with inconsistent results.",
    uses: "Menopause, Skin care",
    properties: "Plant estrogens (isoflavones)",
    cautions: "May increase bleeding risk; avoid with hormone-sensitive cancers, blood thinners, or during pregnancy.",
    imageUrl: "/herbs/red-clover.jpg",
  },
  {
    name: "Raspberry Leaf",
    scientificName: "Rubus idaeus",
    category: "Medicinal",
    summary: "Leaves of the raspberry plant, made into tea. Traditionally used for period cramps and widely used in pregnancy, though its safety in pregnancy hasn't been proven.",
    uses: "Tea, Period cramps, Pregnancy (traditional)",
    properties: "May ease period cramps",
    cautions: "Not proven safe in pregnancy; ask your midwife or doctor first.",
    imageUrl: "/herbs/raspberry-leaf.jpg",
  },
  {
    name: "Chasteberry",
    scientificName: "Vitex agnus-castus",
    category: "Medicinal",
    summary: "The berries of the chaste tree (vitex), recognized in Europe for easing PMS (premenstrual syndrome).",
    uses: "PMS, Breast tenderness, Women's health",
    properties: "May ease PMS",
    cautions: "Not for use during pregnancy or breastfeeding, or with hormone-sensitive cancers.",
    imageUrl: "/herbs/chasteberry.jpg",
  },
  {
    name: "Black Cohosh",
    scientificName: "Actaea racemosa",
    category: "Medicinal",
    summary: "A root used traditionally by Native Americans and recognized in Europe for menopausal hot flushes. Rare liver problems have been reported.",
    uses: "Menopause, Hot flashes",
    properties: "May ease hot flashes",
    cautions: "Stop and see a doctor if you notice dark urine, yellow skin or eyes, or unusual tiredness.",
    imageUrl: "/herbs/black-cohosh.jpg",
  },
  {
    name: "Dong Quai",
    scientificName: "Angelica sinensis",
    category: "Medicinal",
    summary: "A root that is one of the most widely used herbs in traditional Chinese medicine for women's health, including period pain and menopause.",
    uses: "Period pain, Menopause, Women's health",
    properties: "Women's tonic (traditional)",
    cautions: "May increase bleeding with blood thinners; avoid during pregnancy and breastfeeding.",
    imageUrl: "/herbs/dong-quai.jpg",
  },
  {
    name: "Shatavari",
    scientificName: "Asparagus racemosus",
    category: "Medicinal",
    summary: "A root used in Ayurveda as a tonic and to increase breast milk. Research on it is limited.",
    uses: "Breast milk, Menopause, Women's health",
    properties: "Tonic, May increase breast milk (traditional)",
    cautions: "Its safety in pregnancy is uncertain; ask your doctor or midwife first.",
    imageUrl: "/herbs/shatavari.jpg",
  },
  {
    name: "Queen Anne's Lace",
    scientificName: "Daucus carota",
    category: "Medicinal",
    summary: "Wild carrot, whose seeds have long been used in folk medicine to prevent pregnancy. It hasn't been proven safe or effective, and it looks like deadly poison hemlock.",
    uses: "Traditional birth control, Urinary complaints",
    properties: "Traditionally used to prevent pregnancy",
    cautions: "Not reliable birth control; avoid if pregnant or trying to conceive; easily confused with poison hemlock.",
    imageUrl: "/herbs/queen-annes-lace.jpg",
  },
  {
    name: "Maca",
    scientificName: "Lepidium meyenii",
    category: "Medicinal",
    summary: "A root vegetable from the high Andes of Peru, used for centuries as food and to boost energy and fertility. Its effects haven't been proven in rigorous trials.",
    uses: "Energy, Fertility, Sexual health, Menopause",
    properties: "Adaptogen",
    cautions: "Avoid during pregnancy and breastfeeding; may affect testosterone blood tests.",
    imageUrl: "/herbs/maca.jpg",
  },
  {
    name: "Milk Thistle",
    scientificName: "Silybum marianum",
    category: "Medicinal",
    summary: "A tall, purple-flowered thistle from Europe, long used for liver problems. Studies of it and its extract silymarin in liver disease have been conflicting or too limited to show a clear benefit.",
    uses: "Liver support, Indigestion, Breast milk",
    properties: "Traditionally used to support the liver",
    cautions: "May cause allergic reactions in people allergic to ragweed, daisies or related plants.",
    imageUrl: "/herbs/milk-thistle.jpg",
  },
  {
    name: "Dandelion",
    scientificName: "Taraxacum officinale",
    category: "Medicinal",
    summary: "A plant whose root and leaves have long been used for indigestion and, historically, for problems with bile flow. There is very little research on it in people.",
    uses: "Indigestion, Bile flow, Liver and gallbladder (traditional), Appetite, Urinary complaints",
    properties: "May increase urination",
    cautions: "Don't use dandelion medicines if you have gallstones, a blocked bile duct or liver disease.",
    imageUrl: "/herbs/dandelion.jpg",
  },
  {
    name: "Artichoke Leaf",
    scientificName: "Cynara cardunculus",
    category: "Medicinal",
    summary: "Leaves of the artichoke plant, recognized in Europe for indigestion, fullness and bloating. Several small trials suggest it may lower liver enzyme levels in fatty liver disease.",
    uses: "Indigestion, Bloating, Fatty liver",
    properties: "May ease indigestion",
    cautions: "Don't use it if you have gallstones, a blocked bile duct or liver disease, or are allergic to daisy-family plants.",
    imageUrl: "/herbs/artichoke.jpg",
  },
  {
    name: "Chanca Piedra",
    scientificName: "Phyllanthus niruri",
    category: "Medicinal",
    summary: "A plant traditionally used in Malay, Chinese and Ayurvedic medicine for kidney stones and liver problems. It has been studied for both, with mixed results.",
    uses: "Kidney stones, Liver problems, Jaundice, Indigestion",
    properties: "Traditionally used for the liver and kidneys",
    cautions: "Kidney stones and liver disease need medical care; don't use it in place of treatment.",
    imageUrl: "/herbs/chanca-piedra.jpg",
  },
  {
    name: "Burdock",
    scientificName: "Arctium lappa",
    category: "Medicinal",
    summary: "A plant whose root has been eaten as food in Asia for centuries. It is traditionally used as a \"blood purifier\" and for skin problems, but there is little evidence in people.",
    uses: "Skin problems, Appetite, Urinary complaints, Blood purifier (traditional)",
    properties: "Traditionally used as a blood purifier",
    cautions: "Avoid during pregnancy; can cause severe allergic reactions, and one case of liver injury has been reported.",
    imageUrl: "/herbs/burdock.jpg",
  },
  {
    name: "Schisandra",
    scientificName: "Schisandra chinensis",
    category: "Medicinal",
    summary: "A fruit known in Chinese as wu wei zi (\"five-flavor fruit\"), long used in traditional Chinese medicine for the liver, coughs and energy. Studies in people are few and small.",
    uses: "Liver problems, Cough, Energy, Tonic",
    properties: "Tonic, Adaptogen",
    cautions: "Can change blood levels of some medicines, including tacrolimus; it can also lower liver test results.",
    imageUrl: "/herbs/schisandra.jpg",
  },
  {
    name: "Turkey Tail",
    scientificName: "Trametes versicolor",
    category: "Medicinal",
    summary: "A mushroom used in traditional Chinese medicine as a tonic. Extracts from it are used alongside cancer treatment in Japan and China.",
    uses: "Immune support, General health, Cancer care (alongside treatment)",
    properties: "Immune support",
    cautions: "Its safety in pregnancy and breastfeeding isn't known; talk to your doctor before using supplements.",
    imageUrl: "/herbs/turkey-tail.jpg",
  },
  {
    name: "Green Tea",
    scientificName: "Camellia sinensis",
    category: "Medicinal",
    summary: "Unfermented leaves of the tea plant, drunk for thousands of years. Drinking the tea is considered safe, but concentrated green tea extract supplements have rarely caused serious liver damage.",
    uses: "Tea, Weight, Cholesterol, Fatty liver",
    properties: "Antioxidant",
    cautions: "Green tea extract pills have rarely caused severe liver damage; contains caffeine.",
    imageUrl: "/herbs/green-tea.jpg",
  },
  {
    name: "Gold Coin Grass",
    scientificName: "Lysimachia christinae, Desmodium styracifolium",
    category: "Medicinal",
    summary: "A name used in traditional Chinese medicine for two plants, Lysimachia christinae (jin qian cao) and Desmodium styracifolium (guang jin qian cao). Both are used for gallstones and urinary stones; a large trial found a Desmodium extract helped small stones pass.",
    uses: "Gallstones, Kidney stones, Bile flow, Urinary complaints, Jaundice",
    properties: "Traditionally used for gallstones and kidney stones",
    cautions: "These are different plants, and research on one may not apply to the other. Gallstones and kidney stones need medical care.",
    imageUrl: "/herbs/gold-coin-grass.jpg",
  },
  {
    name: "Calendula",
    scientificName: "Calendula officinalis",
    category: "Medicinal",
    summary: "The pot marigold, used in creams and ointments to soothe the skin. It is recognized in Europe for minor skin inflammation such as sunburn and to help minor wounds heal.",
    uses: "Minor wounds, Sunburn, Skin inflammation, Mouth and throat inflammation",
    properties: "May help minor wounds heal",
    cautions: "Can cause skin allergies; don't use it if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/calendula.jpg",
  },
  {
    name: "Horsetail",
    scientificName: "Equisetum arvense",
    category: "Medicinal",
    summary: "A plant recognized in Europe as a traditional medicine for minor urinary complaints and, as a wash or dressing, for superficial wounds. One small trial found a horsetail ointment helped episiotomy wounds heal.",
    uses: "Superficial wounds, Urinary complaints",
    properties: "May increase urination",
    cautions: "Don't use it for urinary complaints if you've been told to limit fluids, for example with serious heart or kidney disease.",
    imageUrl: "/herbs/horsetail.jpg",
  },
  {
    name: "Alfalfa",
    scientificName: "Medicago sativa",
    category: "Medicinal",
    summary: "A widely used food and animal-feed crop, promoted as a supplement for many uses, including lowering cholesterol. Extracts have been studied on skin cells in the lab, but not on skin in people.",
    uses: "Cholesterol, Skin care (lab research), Nutrition",
    properties: "Antioxidant",
    cautions: "Avoid if you have lupus, gout, or are pregnant or breastfeeding; raw sprouts have caused food poisoning.",
    imageUrl: "/herbs/alfalfa.jpg",
  },
  {
    name: "Rosehips",
    scientificName: "Rosa canina",
    category: "Medicinal",
    summary: "The fruit of wild roses such as the dog rose, rich in vitamin C. Rosehip seed oil and powder have been studied for scars and wrinkles in small trials.",
    uses: "Scars, Wrinkles, Skin care, Vitamin C",
    properties: "Antioxidant",
    cautions: "Research on skin use is limited to small studies.",
    imageUrl: "/herbs/rosehips.jpg",
  },
  {
    name: "English Plantain",
    scientificName: "Plantago lanceolata",
    category: "Medicinal",
    summary: "A plant (also called ribwort plantain) whose leaves are recognized in Europe as a traditional medicine for coughs, sore throats and minor skin inflammation.",
    uses: "Skin inflammation, Cough, Sore throat",
    properties: "Soothing (traditional)",
    cautions: "Don't use it if you're allergic to plantain or its pollen.",
    imageUrl: "/herbs/english-plantain.jpg",
  },
  {
    name: "Snakeroot",
    scientificName: "Ageratina pichinchensis",
    category: "Medicinal",
    summary: "A plant native to Mexico, known there as axihuitl, long used in traditional Mexican medicine for skin problems and wounds. Small trials in Mexico have tested extracts for fungal skin and nail infections and leg ulcers.",
    uses: "Fungal skin infections, Nail fungus, Wounds, Skin ulcers",
    properties: "Antifungal",
    cautions: "Other plants are also called snakeroot (for example black cohosh); this page is only about Ageratina pichinchensis.",
    imageUrl: "/herbs/snakeroot.jpg",
  },
  {
    name: "Mugwort",
    scientificName: "Artemisia vulgaris",
    category: "Medicinal",
    summary: "A common plant called the \"mother of herbs\" in the Middle Ages, when it was used on wounds. It is also used in Chinese moxibustion. Mugwort is a major cause of pollen allergy and can cause skin allergies.",
    uses: "Wounds (traditional), Digestion, Moxibustion, Menstrual complaints (traditional)",
    properties: "Bitter, Aromatic",
    cautions: "Avoid during pregnancy (large amounts may cause miscarriage) and if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/mugwort.jpg",
  },
  {
    name: "Neem",
    scientificName: "Azadirachta indica",
    category: "Medicinal",
    summary: "A South Asian tree used in Ayurvedic medicine on the skin and for oral hygiene. Neem works against lice, and a small trial found a neem lotion worked as well as standard treatment for scabies.",
    uses: "Skin conditions, Lice, Scabies, Oral hygiene",
    properties: "Kills lice and pests",
    cautions: "Never swallow neem oil: it has caused severe poisoning in children and adults.",
    imageUrl: "/herbs/neem.jpg",
  },
  {
    name: "Andrographis",
    scientificName: "Andrographis paniculata",
    category: "Medicinal",
    summary: "A bitter herb used across Asia for infections and fevers, and traditionally for skin inflammation and wounds. It has mainly been studied for colds and flu.",
    uses: "Colds and flu, Skin inflammation (traditional), Wounds (traditional)",
    properties: "Bitter tonic",
    cautions: "Can cause allergic reactions and skin rash, and may interact with many medicines.",
    imageUrl: "/herbs/andrographis.jpg",
  },
  {
    name: "Chickweed",
    scientificName: "Stellaria media",
    category: "Medicinal",
    summary: "A wild weed found worldwide, eaten as a leafy green and traditionally used for skin problems such as burns, cuts and scratches. It hasn't been studied in people.",
    uses: "Burns, Cuts, Skin ailments, Food",
    properties: "Soothing (traditional)",
    cautions: "No studies in people have tested its safety or effects.",
    imageUrl: "/herbs/chickweed.jpg",
  },
  {
    name: "Goldenseal",
    scientificName: "Hydrastis canadensis",
    category: "Medicinal",
    summary: "A North American plant with a bright yellow root, used by Native Americans on wounds and for skin and eye conditions. There isn't enough research to know whether it helps any health condition.",
    uses: "Wounds (traditional), Skin and eye irritation (traditional), Colds, Digestion",
    properties: "Bitter tonic",
    cautions: "Affects many medicines, including metformin; don't use in pregnancy, breastfeeding or babies.",
    imageUrl: "/herbs/goldenseal.jpg",
  },
  {
    name: "Passion Flower",
    scientificName: "Passiflora incarnata",
    category: "Medicinal",
    summary: "A climbing vine from the Americas, used as a calming herb since at least the 1500s. It is recognized in Europe for mild stress and to help sleep, and small studies suggest it may ease anxiety.",
    uses: "Sleep, Anxiety, Stress, Calming tea",
    properties: "May make you feel sleepy or relaxed",
    cautions: "Can cause drowsiness; avoid in pregnancy and for 2 weeks before surgery.",
    imageUrl: "/herbs/passion-flower.jpg",
  },
  {
    name: "Holy Basil",
    scientificName: "Ocimum tenuiflorum",
    category: "Medicinal",
    summary: "Tulsi, a highly revered plant in India used in Ayurveda for stress, coughs, asthma and many other conditions. Small studies suggest it may ease stress and anxiety.",
    uses: "Stress, Anxiety, Cough, Asthma (traditional), Memory",
    properties: "Adaptogen",
    cautions: "Most studies were small and done in India; long-term safety isn't well studied.",
    imageUrl: "/herbs/holy-basil.jpg",
  },
  {
    name: "Catnip",
    scientificName: "Nepeta cataria",
    category: "Medicinal",
    summary: "A plant in the mint family traditionally used for colic, coughs, asthma and nervous upset. Its oil is also an effective mosquito repellent.",
    uses: "Colic, Cough, Asthma (traditional), Nervous upset (traditional), Mosquito repellent",
    properties: "May ease cramps",
    cautions: "A toddler became very drowsy after eating a large amount; keep away from children.",
    imageUrl: "/herbs/catnip.jpg",
  },
  {
    name: "Lion's Mane",
    scientificName: "Hericium erinaceus",
    category: "Medicinal",
    summary: "An edible mushroom studied for memory and mood. Small trials suggest it may help thinking in older adults with mild memory problems.",
    uses: "Memory, Focus, Mood, Sleep",
    properties: "Brain support (under study)",
    cautions: "May cause stomach upset, headache or allergic reactions; research is limited.",
    imageUrl: "/herbs/lions-mane.jpg",
  },
  {
    name: "Gotu Kola",
    scientificName: "Centella asiatica",
    category: "Medicinal",
    summary: "A plant used in traditional medicine for circulation, wounds and memory. Small studies suggest possible benefits for anxiety and thinking, but the evidence isn't strong.",
    uses: "Memory, Anxiety, Circulation, Wounds",
    properties: "May help wounds heal",
    cautions: "Liver damage and skin rashes have been reported; not the same as caffeine-containing kola nut.",
    imageUrl: "/herbs/gotu-kola.jpg",
  },
  {
    name: "Siamese Cassia",
    scientificName: "Senna siamea",
    category: "Medicinal",
    summary: "A tree whose leaves are eaten in Thailand, where it is called khi lek and traditionally used for sleep. A calming product made from it caused cases of hepatitis.",
    uses: "Sleep (traditional), Anxiety (traditional), Fever, Food",
    properties: "May make you feel sleepy (in animals)",
    cautions: "Barakol, its calming compound, has caused liver inflammation (hepatitis).",
    imageUrl: "/herbs/siamese-cassia.jpg",
  },
  {
    name: "Brahmi",
    scientificName: "Bacopa monnieri",
    category: "Medicinal",
    summary: "Bacopa, long used in Ayurvedic medicine for nerve and behavior problems. Reviews of trials suggest it may modestly improve memory and attention speed.",
    uses: "Memory, Attention, Learning",
    properties: "Brain tonic (traditional)",
    cautions: "Research on its safety is limited; talk to your doctor before using it.",
    imageUrl: "/herbs/brahmi.jpg",
  },
  {
    name: "Kava",
    scientificName: "Piper methysticum",
    category: "Medicinal",
    summary: "A root from the South Pacific, drunk in ceremonies for thousands of years. It may ease anxiety short term, but it has been linked to rare, sometimes fatal, liver damage.",
    uses: "Anxiety, Relaxation, Ceremonial drink",
    properties: "May ease anxiety",
    cautions: "Linked to serious liver damage; don't combine with alcohol or sleep and anxiety medicines.",
    imageUrl: "/herbs/kava.jpg",
  },
  {
    name: "Mullein",
    scientificName: "Verbascum thapsus",
    category: "Medicinal",
    summary: "A plant whose flowers are made into tea and recognized in Europe as a traditional medicine for sore throat with a dry cough and cold.",
    uses: "Sore throat, Dry cough, Colds, Tea",
    properties: "Soothing (traditional)",
    cautions: "Not recommended for children under 12 or during pregnancy and breastfeeding.",
    imageUrl: "/herbs/mullein.jpg",
  },
  {
    name: "Elecampane",
    scientificName: "Inula helenium",
    category: "Medicinal",
    summary: "A root used for centuries in European medicine, including medieval Ireland, for coughs, bronchitis and other chest complaints. Germany's Commission E didn't approve it, citing weak evidence and possible side effects.",
    uses: "Cough, Bronchitis, Chest congestion",
    properties: "May help loosen mucus (traditional)",
    cautions: "Not officially approved as a medicine because of weak evidence and possible side effects; may cause skin allergies.",
    imageUrl: "/herbs/elecampane.jpg",
  },
  {
    name: "Eucalyptus",
    scientificName: "Eucalyptus globulus",
    category: "Medicinal",
    summary: "Leaves of the eucalyptus tree, taken as tea or inhaled in steam, and recognized in Europe as a traditional medicine for cough with a cold.",
    uses: "Cough, Colds, Steam inhalation, Tea",
    properties: "May help loosen mucus (traditional)",
    cautions: "Never use it in children under 30 months: it can cause a dangerous tightening of the vocal cords.",
    imageUrl: "/herbs/eucalyptus.jpg",
  },
  {
    name: "Licorice",
    scientificName: "Glycyrrhiza glabra",
    category: "Medicinal",
    summary: "A root used since ancient times in Egyptian, Greek, Chinese and Indian medicine for coughs, asthma and wounds. Recognized in Europe for cough with a cold and for indigestion, but too much can raise blood pressure and upset heart rhythm.",
    uses: "Cough, Sore throat, Indigestion, Heartburn",
    properties: "May help loosen mucus",
    cautions: "Large amounts or long-term use can cause high blood pressure, low potassium and dangerous heart rhythms.",
    imageUrl: "/herbs/licorice.jpg",
  },
  {
    name: "Eyebright",
    scientificName: "Euphrasia officinalis",
    category: "Medicinal",
    summary: "A plant traditionally used on the eyes and in nasal ointments for colds. European regulators declined to approve it because its benefits aren't documented and home-made eye washes aren't safe.",
    uses: "Eye irritation (traditional), Nasal irritation with colds (traditional)",
    properties: "Traditionally used for eye irritation",
    cautions: "Don't put home-made eyebright preparations in your eyes: they aren't hygienic or safe.",
    imageUrl: "/herbs/eyebright.jpg",
  },
  {
    name: "Grindelia",
    scientificName: "Grindelia robusta",
    category: "Medicinal",
    summary: "Gumweed, a daisy-family plant whose above-ground parts are recognized in Europe as a traditional medicine for cough with a cold in adults.",
    uses: "Cough, Colds",
    properties: "Traditionally used for cough",
    cautions: "For adults only; avoid if you're allergic to daisy-family plants.",
    imageUrl: "/herbs/grindelia.jpg",
  },
  {
    name: "Horehound",
    scientificName: "Marrubium vulgare",
    category: "Medicinal",
    summary: "White horehound, a bitter mint-family herb recognized in Europe as a traditional medicine to help bring up phlegm with a cold, and for indigestion and poor appetite.",
    uses: "Cough, Chest congestion, Indigestion, Appetite",
    properties: "May help loosen mucus, Bitter",
    cautions: "Don't use it with liver disease, a blocked bile duct or a bowel blockage; ask a doctor first if you have gallstones or an ulcer.",
    imageUrl: "/herbs/horehound.jpg",
  },
  {
    name: "Osha",
    scientificName: "Ligusticum porteri",
    category: "Medicinal",
    summary: "A root from the Rocky Mountains, long used by Hispanic and Native American peoples for colds, flu and chest infections. It has only been studied in the lab.",
    uses: "Colds, Flu, Chest infections, Indigestion",
    properties: "Traditionally used for colds and flu",
    cautions: "No studies in people have tested its safety or effects.",
    imageUrl: "/herbs/osha.jpg",
  },
  {
    name: "Yerba Santa",
    scientificName: "Eriodictyon californicum",
    category: "Medicinal",
    summary: "A shrub from the southwestern United States and northern Mexico whose leaves have been used by Indigenous peoples for centuries, especially for breathing problems.",
    uses: "Breathing problems (traditional), Cough",
    properties: "Traditionally used for breathing problems",
    cautions: "It hasn't been studied in people for any health use.",
    imageUrl: "/herbs/yerba-santa.jpg",
  },
  {
    name: "Wild Cherry",
    scientificName: "Prunus serotina",
    category: "Medicinal",
    summary: "Black cherry (capulín), a North American tree used in Mexican folk medicine for cough, high blood pressure and digestive problems. Its seeds and leaves contain compounds that can release cyanide.",
    uses: "Cough (traditional), Digestion (traditional)",
    properties: "Traditionally used for cough",
    cautions: "Seeds and leaves contain compounds that release cyanide when crushed.",
    imageUrl: "/herbs/wild-cherry.jpg",
  },
  {
    name: "Pleurisy Root",
    scientificName: "Asclepias tuberosa",
    category: "Medicinal",
    summary: "A milkweed whose root was traditionally used for breathing problems and to loosen mucus. It contains heart-affecting compounds, and its sap has injured people's eyes.",
    uses: "Breathing problems (traditional), Chest congestion (traditional)",
    properties: "Contains heart-affecting compounds (cardiac glycosides)",
    cautions: "Contains cardiac glycosides; its sap can seriously irritate the eyes.",
    imageUrl: "/herbs/pleurisy-root.jpg",
  },
  {
    name: "Boswellia",
    scientificName: "Boswellia serrata",
    category: "Medicinal",
    summary: "Indian frankincense, a gum resin from a tree used for centuries in Ayurveda for inflammation. It is marketed for arthritis and colitis, and has been studied with curcumin for IBS bloating.",
    uses: "Inflammation, Arthritis, Colitis, IBS",
    properties: "May help reduce inflammation",
    cautions: "Likely safe by mouth in studied doses; little is known about use in pregnancy or breastfeeding.",
    imageUrl: "/herbs/boswellia.jpg",
  },
  {
    name: "Triphala",
    scientificName: "Phyllanthus emblica, Terminalia bellirica, Terminalia chebula",
    category: "Medicinal",
    summary: "A classic Ayurvedic blend of three dried fruits (amalaki, bibhitaki and haritaki), used as a cornerstone of digestive care and as a laxative. Research in people is limited.",
    uses: "Constipation, Digestion, Gut health",
    properties: "Laxative (traditional), Antioxidant",
    cautions: "Research on its safety in people is limited.",
    imageUrl: "/herbs/triphala.jpg",
  },
  {
    name: "Berberine",
    scientificName: "Berberis vulgaris",
    category: "Medicinal",
    summary: "A natural compound found in barberry (shown here) and other plants such as goldenseal. It is widely used in China for diarrhea, and has been studied for H. pylori infection and blood sugar.",
    uses: "Diarrhea, H. pylori, Blood sugar, Gut health",
    properties: "Antibacterial",
    cautions: "Can harm newborns: avoid in pregnancy, breastfeeding and babies.",
    imageUrl: "/herbs/berberine.jpg",
  },
  {
    name: "Wormwood",
    scientificName: "Artemisia absinthium",
    category: "Medicinal",
    summary: "A bitter herb recognized in Europe as a traditional medicine for temporary loss of appetite and mild heartburn and stomach and gut complaints.",
    uses: "Loss of appetite, Indigestion, Heartburn",
    properties: "Bitter",
    cautions: "For adults only; don't use it with liver disease, a blocked bile duct, or during pregnancy or breastfeeding.",
    imageUrl: "/herbs/wormwood.jpg",
  },
  {
    name: "Black Walnut",
    scientificName: "Juglans nigra",
    category: "Medicinal",
    summary: "A North American tree whose nut hulls contain juglone and other compounds. Black walnut hull is an ingredient in herbal gut formulas, but it hasn't been studied on its own in people.",
    uses: "Gut formulas (SIBO, parasites)",
    properties: "Contains juglone",
    cautions: "It hasn't been tested on its own in people; its safety isn't known.",
    imageUrl: "/herbs/black-walnut.jpg",
  },
  {
    name: "Soursop",
    scientificName: "Annona muricata",
    category: "Medicinal",
    summary: "A tropical fruit (graviola) used in folk medicine for stomachache, diarrhea and intestinal parasites. Eating it has been linked to more severe Parkinson's disease in the Caribbean.",
    uses: "Stomachache, Diarrhea, Intestinal parasites, Food",
    properties: "Traditionally used for the gut",
    cautions: "Contains annonacin, a compound toxic to nerve cells; linked to more severe Parkinson's disease.",
    imageUrl: "/herbs/soursop.jpg",
  },
  {
    name: "Moringa",
    scientificName: "Moringa oleifera",
    category: "Medicinal",
    summary: "A nutritious tree used as food and traditional medicine, including for stomach and gut problems. In animal studies it helped heal stomach ulcers; in people it has been studied mainly for blood pressure and blood sugar.",
    uses: "Nutrition, Stomach ulcers, Blood pressure, Blood sugar",
    properties: "Antioxidant, Nutritious",
    cautions: "Large clinical trials are lacking, so its effects and safety aren't well established.",
    imageUrl: "/herbs/moringa.jpg",
  },
  {
    name: "Slippery Elm",
    scientificName: "Ulmus rubra",
    category: "Medicinal",
    summary: "The inner bark of a North American elm, taken by mouth for sore throat and stomach upset and used on the skin for rashes. It is generally recognized as safe.",
    uses: "Stomach upset, Sore throat, Skin irritation",
    properties: "Soothing (traditional)",
    cautions: "Generally recognized as safe; it hasn't been linked to liver injury.",
    imageUrl: "/herbs/slippery-elm.jpg",
  },
  {
    name: "Marshmallow Root",
    scientificName: "Althaea officinalis",
    category: "Medicinal",
    summary: "A root recognized in Europe as a traditional medicine for mouth and throat irritation with a dry cough, and for mild stomach and gut discomfort.",
    uses: "Stomach discomfort, Sore throat, Dry cough",
    properties: "Soothing (traditional)",
    cautions: "May slow absorption of other medicines; take it at least 30 to 60 minutes apart from them.",
    imageUrl: "/herbs/marshmallow-root.jpg",
  },
  {
    name: "Elderberry",
    scientificName: "Sambucus nigra",
    category: "Medicinal",
    summary: "The European elder, whose berries are used in folk medicine for colds and flu and whose flowers are recognized in Europe for early cold symptoms. Raw berries, leaves and stems are poisonous.",
    uses: "Colds, Flu, Immune support",
    properties: "Immune support",
    cautions: "Never eat raw or unripe berries, leaves or stems: they contain cyanide-producing substances. Cooking removes them.",
    imageUrl: "/herbs/elderberry.jpg",
  },
  {
    name: "Astragalus",
    scientificName: "Astragalus membranaceus",
    category: "Medicinal",
    summary: "A root (huang qi) used for centuries in traditional Chinese medicine and promoted to strengthen the immune system. There isn't enough reliable evidence to know whether it helps any condition.",
    uses: "Immune support, Colds, Fatigue, Kidney health",
    properties: "Immune support",
    cautions: "Avoid with autoimmune diseases or immune-suppressing medicines.",
    imageUrl: "/herbs/astragalus.jpg",
  },
  {
    name: "American Ginseng",
    scientificName: "Panax quinquefolius",
    category: "Medicinal",
    summary: "North American ginseng, a root studied for preventing colds. Taken for 8 to 16 weeks, it shortened colds in healthy adults in a small number of trials.",
    uses: "Colds, Immune support",
    properties: "Immune support",
    cautions: "Can cause digestive upset; evidence on preventing colds is inconsistent.",
    imageUrl: "/herbs/american-ginseng.jpg",
  },
  {
    name: "Quercetin",
    scientificName: "Plant flavonoid (found in apples, onions and other foods)",
    category: "Medicinal",
    summary: "A natural plant compound found in apples, onions, grapes, citrus and parsley, and sold as a supplement. In a trial of 1,002 people it didn't prevent colds overall.",
    uses: "Immune support, Colds, Antioxidant",
    properties: "Antioxidant",
    cautions: "Very little is absorbed from ordinary supplements; research in people is mixed.",
    imageUrl: "/herbs/quercetin.jpg",
  },
  {
    name: "Chaga",
    scientificName: "Inonotus obliquus",
    category: "Medicinal",
    summary: "A dark, crusty fungus that grows on birch trees, long used as a folk remedy in Siberia and Russia for immunity. It is very high in oxalate, and long-term use has caused kidney damage.",
    uses: "Immune support, Digestive tea (traditional)",
    properties: "Immune support (traditional)",
    cautions: "Very high in oxalate; long-term use has caused kidney damage.",
    imageUrl: "/herbs/chaga.jpg",
  },
  {
    name: "Amla",
    scientificName: "Phyllanthus emblica",
    category: "Medicinal",
    summary: "Indian gooseberry, a fruit rich in vitamin C and antioxidants, used in Ayurveda and as one of the three fruits in Triphala. Trials suggest it may lower cholesterol, blood sugar and a marker of inflammation.",
    uses: "Immune support, Cholesterol, Blood sugar, Vitamin C",
    properties: "Antioxidant",
    cautions: "Research has been in small trials.",
    imageUrl: "/herbs/amla.jpg",
  },
  {
    name: "Giloy (Guduchi)",
    scientificName: "Tinospora cordifolia",
    category: "Medicinal",
    summary: "An Ayurvedic climbing vine promoted in India as an immunity booster, including during COVID-19. Cases of liver injury have been reported, though some may involve a look-alike plant.",
    uses: "Immune support, Fever, Liver (traditional)",
    properties: "Immune support (traditional)",
    cautions: "Liver injury, including autoimmune-like hepatitis, has been reported; stop and see a doctor if you notice yellow skin or dark urine.",
    imageUrl: "/herbs/giloy.jpg",
  },
  {
    name: "Katuki",
    scientificName: "Picrorhiza kurroa",
    category: "Medicinal",
    summary: "Kutki, a bitter root used in Ayurveda for thousands of years for fever, jaundice, the liver and breathing problems. It is now endangered in the wild.",
    uses: "Fever, Liver, Immune support, Breathing problems",
    properties: "Bitter, Immune support (traditional)",
    cautions: "Can cause miscarriage; don't use during pregnancy.",
    imageUrl: "/herbs/katuki.jpg",
  },
  {
    name: "Cloves",
    scientificName: "Syzygium aromaticum",
    category: "Medicinal",
    summary: "A kitchen spice from the clove tree, whose oil is recognized in Europe for toothache and minor mouth and throat inflammation. In the lab, clove oil kills bacteria and fungi.",
    uses: "Toothache, Mouth and throat inflammation, Spice",
    properties: "Kills germs (in lab tests)",
    cautions: "Clove oil can irritate the mouth and gums and cause allergies.",
    imageUrl: "/herbs/cloves.jpg",
  },
  {
    name: "Lion's Ear",
    scientificName: "Leonotis nepetifolia",
    category: "Medicinal",
    summary: "A plant in the mint family, known as shandilay in Trinidad, where it's a popular traditional remedy for colds and coughs. Research so far is limited to lab and animal studies.",
    uses: "Colds, Cough, Fever, Asthma (traditional), Diabetes (traditional)",
    properties: "May fight germs (in lab tests), Antioxidant (in lab tests)",
    cautions: "Little is known about its safety; flower extracts caused birth defects in zebrafish embryos.",
    imageUrl: "/herbs/lions-ear.jpg",
  },
  {
    name: "Duppy Gun",
    scientificName: "Ruellia tuberosa",
    category: "Medicinal",
    summary: "Ruellia tuberosa, also called Mexican bluebell, a folk medicine for diabetes in Asia. It lowered blood sugar in diabetic rats but hasn't been tested in people.",
    uses: "Blood sugar (traditional), High blood pressure (traditional), Fever, Pain",
    properties: "May lower blood sugar (in animal studies)",
    cautions: "Hasn't been studied in people, so its safety is unknown.",
    imageUrl: "/herbs/duppy-gun.jpg",
  },
  {
    name: "Search Mi Heart",
    scientificName: "Rhytidophyllum tomentosum",
    category: "Medicinal",
    summary: "A Jamaican plant whose dried leaves are made into a bush tea, traditionally used for colds and flu, the heart, breathing problems and digestion. It hasn't been studied in research.",
    uses: "Colds, Flu, Heart (traditional), Blood pressure (traditional), Asthma, Chest congestion, Indigestion, Bush tea",
    properties: "Folk remedy (not studied)",
    cautions: "Its safety hasn't been studied; check with a doctor first if you're pregnant, breastfeeding, or have heart disease or high blood pressure.",
    imageUrl: "/herbs/search-mi-heart.jpg",
  },
  {
    name: "Susumber",
    scientificName: "Solanum torvum",
    category: "Culinary",
    summary: "Turkey berry, a small berry from the nightshade family cooked in Jamaican dishes and used in traditional medicine in Asia, Africa and South America. Some batches of berries have caused serious poisoning.",
    uses: "Food, Cough (traditional), High blood pressure (traditional), Worms (traditional)",
    properties: "Edible berry",
    cautions: "Some batches have caused serious poisoning with stroke-like symptoms such as slurred speech and unsteady walking; get emergency help if these appear after eating it.",
    imageUrl: "/herbs/susumber.jpg",
  },
  {
    name: "Purslane",
    scientificName: "Portulaca oleracea",
    category: "Culinary",
    summary: "A leafy plant eaten as a vegetable and used as a folk medicine, called pussley in Trinidad. Reviews of trials found it may lower fasting blood sugar a little and improve cholesterol in people with type 2 diabetes.",
    uses: "Vegetable, Blood sugar, Cholesterol, Shortness of breath (traditional), Dysentery (traditional)",
    properties: "Rich in omega-3 and vitamins C and E",
    cautions: "High in oxalates, which reduce how well minerals are absorbed; blanching or pickling lowers them.",
    imageUrl: "/herbs/purslane.jpg",
  },
  {
    name: "Periwinkle",
    scientificName: "Catharanthus roseus",
    category: "Medicinal",
    summary: "Madagascar periwinkle, a garden plant used in Caribbean folk medicine for diabetes and the source of two cancer drugs. The plant can be poisonous.",
    uses: "Diabetes (traditional), Cancer (traditional)",
    properties: "Lowers blood sugar (in animal studies)",
    cautions: "Contains highly poisonous compounds; drinking periwinkle juice has caused liver damage and stomach ulcers.",
    imageUrl: "/herbs/periwinkle.jpg",
  },
  {
    name: "Pepper Elder",
    scientificName: "Piper amalago",
    category: "Medicinal",
    summary: "A plant in the pepper family whose leaves are made into a Jamaican bush tea for colds and flu. Research so far is mostly in rats.",
    uses: "Colds, Flu, Inflammation (traditional), Anxiety (traditional), Wounds",
    properties: "May increase urination (in animal studies)",
    cautions: "Long-term daily use caused liver and blood changes in rats; use with caution, especially for long periods.",
    imageUrl: "/herbs/pepper-elder.jpg",
  },
  {
    name: "Devil's Horsewhip",
    scientificName: "Achyranthes aspera",
    category: "Medicinal",
    summary: "Prickly chaff flower, a weedy plant used in folk medicine around the world, including for menstrual problems and fertility control. Research so far is in lab and animal studies.",
    uses: "Menstrual problems (traditional), Fertility control (traditional)",
    properties: "Estrogen-like (in lab tests), Antioxidant (in lab tests)",
    cautions: "High doses harmed developing babies in pregnant rats.",
    imageUrl: "/herbs/devils-horsewhip.jpg",
  },
  {
    name: "Epazote",
    scientificName: "Dysphania ambrosioides",
    category: "Medicinal",
    summary: "An herb used in Jamaican and Latin American folk medicine against worms. It can cause serious, even deadly, poisoning, especially in children.",
    uses: "Worms (traditional), Fever (traditional), Pain (traditional)",
    properties: "Kills parasites (in lab tests)",
    cautions: "Can cause deadly poisoning, especially in babies and children; a child died after repeated strong doses of the tea.",
    imageUrl: "/herbs/epazote.jpg",
  },
  {
    name: "Jamaican Rat Ears",
    scientificName: "Peperomia pellucida",
    category: "Medicinal",
    summary: "A small weed of damp, shady places, also called shining bush, used in Caribbean folk medicine as a cooling remedy and for skin sores. Research so far is limited and often weak.",
    uses: "Cooling (traditional), Skin sores, Belly pain, Blood pressure",
    properties: "Antioxidant (in lab tests)",
    cautions: "Mildly toxic in animal studies; its safety in people hasn't been well studied.",
    imageUrl: "/herbs/jamaican-rat-ears.jpg",
  },
  {
    name: "Ra-Moon",
    scientificName: "Trophis racemosa",
    category: "Medicinal",
    summary: "Ramoon, a Jamaican tree whose bark is made into tea and roots drinks as a traditional remedy for libido, and whose leaves feed livestock. It hasn't been studied in people.",
    uses: "Libido (traditional), Roots drinks, Livestock fodder",
    properties: "Folk remedy (not studied in people)",
    cautions: "Its safety hasn't been studied.",
    imageUrl: "/herbs/ra-moon.jpg",
  },
  {
    name: "Mauby Bark",
    scientificName: "Colubrina arborescens",
    category: "Culinary",
    summary: "The bark used to make mauby, a bitter Caribbean drink and folk remedy. A very small study suggested it may lower blood pressure in some people.",
    uses: "Mauby drink, Blood pressure",
    properties: "Bitter",
    cautions: "May interact with the blood thinner warfarin; talk to your doctor before drinking it if you take warfarin.",
    imageUrl: "/herbs/mauby-bark.jpg",
  },
  {
    name: "John Charles",
    scientificName: "Hyptis verticillata",
    category: "Medicinal",
    summary: "A Caribbean bush in the mint family, used since Maya and Aztec times for breathing, digestive, women's health and skin problems. It hasn't been tested in clinical trials.",
    uses: "Breathing problems, Digestion, Women's health, Skin conditions, Muscle and joint pain",
    properties: "May help reduce inflammation (in lab tests), Fights germs (in lab tests)",
    cautions: "Not tested in people, so its safety and effects are unknown.",
    imageUrl: "/herbs/john-charles.jpg",
  },
  {
    name: "Strong Back Root",
    scientificName: "Morinda royoc",
    category: "Medicinal",
    summary: "Redgal, a root boiled into Jamaica's \"strong back\" roots tonic, used by men for impotence and stamina. It hasn't been studied in people.",
    uses: "Roots tonic, Impotence (traditional), Stamina (traditional), Stomach pain (traditional)",
    properties: "Kills Giardia (in lab tests)",
    cautions: "Its safety hasn't been studied.",
    imageUrl: "/herbs/strong-back-root.jpg",
  },
  {
    name: "Penny Royal",
    scientificName: "Clinopodium brownei",
    category: "Medicinal",
    summary: "Jamaican pennyroyal, one of the island's popular bush medicines for breathing and digestive problems. It is a different plant from European pennyroyal, but its oil contains the same toxic compound, pulegone.",
    uses: "Breathing problems, Digestion, Pain (traditional)",
    properties: "Antioxidant (in lab tests)",
    cautions: "Its oil contains pulegone, the compound in European pennyroyal oil, which has caused deadly liver damage.",
    imageUrl: "/herbs/penny-royal.jpg",
  },
  {
    name: "Gungo Peas",
    scientificName: "Cajanus cajan",
    category: "Culinary",
    summary: "Pigeon peas, a major food crop around the world. The leaves are used in Chinese medicine for bone conditions.",
    uses: "Food, Bone conditions (leaves, traditional)",
    properties: "Source of flavonoids",
    cautions: "No specific safety concerns were found in the sources reviewed.",
    imageUrl: "/herbs/gungo-peas.jpg",
  },
  {
    name: "Shame O' Lady",
    scientificName: "Mimosa pudica",
    category: "Medicinal",
    summary: "The sensitive plant, whose leaves fold up when touched. TRAMIL, the Caribbean traditional-medicine network, recommends it as a tea for period cramps.",
    uses: "Period cramps, Dysentery (traditional), Wounds (traditional), Piles (traditional)",
    properties: "Fights bacteria (in lab tests)",
    cautions: "Not for use during pregnancy or breastfeeding, or in children under 12.",
    imageUrl: "/herbs/shame-o-lady.jpg",
  },
  {
    name: "Vervain",
    scientificName: "Stachytarpheta jamaicensis",
    category: "Medicinal",
    summary: "Called vervain in Jamaica and vervine in Antigua and Trinidad, a weedy plant whose leaves make a \"cooling\" tea used for the stomach, colds and coughs, and to clean wounds.",
    uses: "Cooling tea, Indigestion, Colds, Cough, Wounds",
    properties: "Fights bacteria and fungi (in lab tests)",
    cautions: "Not recommended during pregnancy or if you have low blood pressure.",
    imageUrl: "/herbs/vervain.jpg",
  },
  {
    name: "Dog's Blood",
    scientificName: "Rivina humilis",
    category: "Culinary",
    summary: "A small plant with red berries, known in Jamaica as dogberry and elsewhere as pigeon berry or blood berry. Its leaves are cooked as a leafy green; research so far is in the lab and in rats.",
    uses: "Leafy green, Berries, Blood sugar",
    properties: "Antioxidant (in lab tests)",
    cautions: "Hasn't been studied in people, so its safety as a medicine is unknown.",
    imageUrl: "/herbs/dogs-blood.jpg",
  },
  {
    name: "Leaf of Life",
    scientificName: "Bryophyllum pinnatum",
    category: "Medicinal",
    summary: "One of Jamaica's most popular bush medicines, used for colds and flu. In Switzerland, tablets made from its leaf juice have been studied for overactive bladder and sleep.",
    uses: "Colds, Flu, Overactive bladder, Sleep, Period pain",
    properties: "May ease pain and inflammation (in lab tests)",
    cautions: "Contains bufadienolides, compounds that can be toxic; its safety needs more study.",
    imageUrl: "/herbs/leaf-of-life.jpg",
  },
  {
    name: "Avocado Leaf",
    scientificName: "Persea americana",
    category: "Medicinal",
    summary: "Leaves of the avocado tree, made into a tea and used in Caribbean folk medicine for high blood pressure. They lowered blood pressure in rats but haven't been tested in people.",
    uses: "High blood pressure (traditional), Tea",
    properties: "May lower blood pressure (in animal studies)",
    cautions: "Not studied in people; its safety is unknown.",
    imageUrl: "/herbs/avocado-leaf.jpg",
  },
  {
    name: "Sarsaparilla",
    scientificName: "Smilax ornata",
    category: "Medicinal",
    summary: "A plant whose root is boiled into Jamaican roots tonics and used for colds and flu. Research on sarsaparilla plants is mostly preliminary lab and animal work.",
    uses: "Roots tonic, Colds, Flu, Stamina (traditional), Skin (traditional)",
    properties: "Antioxidant (in lab tests)",
    cautions: "Most research is preliminary; its safety in people hasn't been well studied.",
    imageUrl: "/herbs/sarsaparilla.jpg",
  },
  {
    name: "Damiana",
    scientificName: "Turnera diffusa",
    category: "Medicinal",
    summary: "A plant used in folk medicine as an aphrodisiac. Lab and animal studies suggest effects on sexual function, but it hasn't been tested on its own in people.",
    uses: "Aphrodisiac (traditional), Sexual health",
    properties: "Antioxidant (in lab tests)",
    cautions: "Not tested on its own in people; its safety is unknown.",
    imageUrl: "/herbs/damiana.jpg",
  },
  {
    name: "Ackee Leaf",
    scientificName: "Blighia sapida",
    category: "Medicinal",
    summary: "Leaves of the ackee tree, whose fruit is Jamaica's national dish. The leaves are used in folk medicine for pain, fever and stomach problems. Unripe ackee fruit is poisonous.",
    uses: "Pain (traditional), Fever (traditional), Stomach ache (traditional), Skin (traditional)",
    properties: "May relieve pain (in animal studies)",
    cautions: "Unripe ackee fruit contains hypoglycin A, which has caused deadly poisoning.",
    imageUrl: "/herbs/ackee-leaf.jpg",
  },
  {
    name: "Jack in the Bush",
    scientificName: "Chromolaena odorata",
    category: "Medicinal",
    summary: "One of Jamaica's most popular bush teas for colds and flu, also used in Africa and Asia for fever, wounds and diabetes. Research so far is in the lab and in animals.",
    uses: "Colds, Flu, Fever, Wounds, Diabetes (traditional)",
    properties: "Antioxidant (in lab tests), May help wounds heal (in animal studies)",
    cautions: "Its safety in people hasn't been studied; pyrrolizidine alkaloids have been found in its roots.",
    imageUrl: "/herbs/jack-in-the-bush.jpg",
  },
  {
    name: "Uva Ursi",
    scientificName: "Arctostaphylos uva-ursi",
    category: "Medicinal",
    summary: "Bearberry leaf, recognised in Europe as a traditional remedy for mild, repeated bladder infections in adult women. Use it for no more than a week.",
    uses: "Bladder infections, Urinary tract",
    properties: "Kills bacteria (in lab tests)",
    cautions: "Only for adult women; don't use with kidney problems or for more than 1 week.",
    imageUrl: "/herbs/uva-ursi.jpg",
  },
  {
    name: "Yarrow",
    scientificName: "Achillea millefolium",
    category: "Medicinal",
    summary: "An herb recognised in Europe as a traditional remedy for loss of appetite, mild digestive problems, period cramps and small wounds.",
    uses: "Appetite, Digestion, Bloating, Period cramps, Small wounds",
    properties: "May ease cramps",
    cautions: "Don't use if you're allergic to plants in the daisy family; only for those over 12.",
    imageUrl: "/herbs/yarrow.jpg",
  },
  {
    name: "Star Anise",
    scientificName: "Illicium verum",
    category: "Culinary",
    summary: "The star-shaped fruit of an evergreen tree, used as a spice and in traditional Chinese medicine. Don't give star anise tea to babies: it has made infants seriously ill.",
    uses: "Cooking spice, Stomach pain (traditional), Infant colic (traditional; not safe)",
    properties: "Antioxidant (in lab tests), Kills bacteria (in lab tests)",
    cautions: "Don't give star anise tea to babies; toxic Japanese star anise can be mixed in and looks the same.",
    imageUrl: "/herbs/star-anise.jpg",
  },
  {
    name: "Calamus Root",
    scientificName: "Acorus calamus",
    category: "Medicinal",
    summary: "The root of sweet flag, a marsh plant used in traditional medicine around the world for stomach cramps and asthma. It contains beta-asarone, which caused cancer in animal studies; adding it to food is banned in the US.",
    uses: "Stomach cramps (traditional), Dysentery (traditional), Asthma (traditional), Worms (traditional)",
    properties: "",
    cautions: "Contains beta-asarone, which caused cancer in rodents; calamus is banned as a food ingredient in the US.",
    imageUrl: "/herbs/calamus-root.jpg",
  },
  {
    name: "Skullcap",
    scientificName: "Scutellaria lateriflora",
    category: "Medicinal",
    summary: "A North American mint-family herb, taken as a tea or extract for anxiety, stress and sleep. It has been linked to rare cases of liver injury, often in mixed products.",
    uses: "Anxiety, Stress, Sleep, Period problems (traditional)",
    properties: "May lift mood (one small study)",
    cautions: "Rare liver injury has been reported; some products were mixed with germander, which harms the liver.",
    imageUrl: "/herbs/skullcap.jpg",
  },
  {
    name: "Feverfew",
    scientificName: "Tanacetum parthenium",
    category: "Medicinal",
    summary: "A daisy-like herb recognised in Europe as a traditional remedy to help prevent migraines. Research results are mixed. Don't take it during pregnancy.",
    uses: "Migraine prevention, Headache, Fever (traditional)",
    properties: "May reduce how often migraines happen (mixed evidence)",
    cautions: "Don't use during pregnancy or if you're allergic to daisy-family plants; stop 2 weeks before surgery.",
    imageUrl: "/herbs/feverfew.jpg",
  },
  {
    name: "Bee Balm",
    scientificName: "Monarda didyma",
    category: "Medicinal",
    summary: "A red-flowered North American mint, also called Oswego tea, used by the Cherokee as a tea and as a poultice for colds and headaches. Human research is very limited.",
    uses: "Colds (traditional), Headache (traditional), Tea",
    properties: "Kills bacteria and fungi (in lab tests), Antioxidant (in lab tests)",
    cautions: "The Cherokee traditionally used bee balm tea to cause miscarriage.",
    imageUrl: "/herbs/bee-balm.jpg",
  },
  {
    name: "Batana",
    scientificName: "Elaeis oleifera",
    category: "Medicinal",
    summary: "An oil from the nuts of the American oil palm, used for generations by the Miskito people of Honduras to care for hair and skin. There's no good evidence that it regrows hair.",
    uses: "Hair care, Skin care",
    properties: "Moisturizes hair and scalp",
    cautions: "Can occasionally irritate the scalp; patch-test first if you're allergic to nuts or palm oil.",
    imageUrl: "/herbs/batana.jpg",
  },
  {
    name: "Comfrey",
    scientificName: "Symphytum officinale",
    category: "Medicinal",
    summary: "A plant whose root is made into creams for minor sprains and bruises, recognised in Europe as a traditional remedy. Never take comfrey by mouth: it contains substances that damage the liver.",
    uses: "Sprains, Bruises, Back pain, Joint pain",
    properties: "May relieve pain (on the skin)",
    cautions: "Never take it by mouth; don't put it on broken skin or use it for more than 10 days.",
    imageUrl: "/herbs/comfrey.jpg",
  },
  {
    name: "Blue Lotus",
    scientificName: "Nymphaea caerulea",
    category: "Medicinal",
    summary: "A water lily that was used in rituals in ancient Egypt. It's now sold as teas, vapes and gummies for calming or euphoric effects, and has sent some users to the emergency room.",
    uses: "Calming (traditional), Rituals (historical)",
    properties: "",
    cautions: "Not regulated; has caused confusion, agitation, hallucinations and, in one case, seizures.",
    imageUrl: "/herbs/blue-lotus.jpg",
  },
  {
    name: "Chaney Root",
    scientificName: "Smilax balbisiana",
    category: "Medicinal",
    summary: "A Jamaican climbing plant related to sarsaparilla. Its root is boiled into the popular \"root tonic\" drunk for stamina, and into teas for colds and flu. It hasn't been studied in people.",
    uses: "Root tonic (traditional), Stamina (traditional), Impotence (traditional), Colds and flu (traditional)",
    properties: "",
    cautions: "Not studied in people; homemade root drinks can carry pesticides or germs.",
    imageUrl: "/herbs/chaney-root.jpg",
  },
  {
    name: "Eleuthera",
    scientificName: "Croton eluteria",
    category: "Medicinal",
    summary: "The bitter, aromatic bark of a small Bahamian tree, also called cascarilla. It was once a standard medicine for indigestion, gas, diarrhea and vomiting, and is now mainly a flavoring for drinks.",
    uses: "Indigestion (traditional), Gas (traditional), Diarrhea (traditional), Vomiting (traditional), Flavoring",
    properties: "Bitter tonic (traditional)",
    cautions: "Old medical texts warned it can cause unpleasant symptoms if used too freely.",
    imageUrl: "/herbs/eleuthera.jpg",
  },
  {
    name: "Calea Zacatechichi",
    scientificName: "Calea zacatechichi",
    category: "Medicinal",
    summary: "A Mexican shrub in the daisy family, known as dream herb, used in rituals to bring on vivid dreams and in folk medicine for coughs, asthma and stomach problems. Its safety hasn't been properly studied.",
    uses: "Dreams (ritual), Cough (traditional), Asthma (traditional), Stomach problems (traditional)",
    properties: "May cause light sleep and more dream recall (one small study)",
    cautions: "Large doses caused vomiting in animals, and lab tests found it harmed kidney and brain cells.",
    imageUrl: "/herbs/calea-zacatechichi.jpg",
  },
  {
    name: "Marigold",
    scientificName: "Tagetes erecta",
    category: "Medicinal",
    summary: "The orange-flowered Mexican marigold, or cempasúchil, used in folk medicine from Mexico to India for fevers, colds, stomach upsets and skin sores. It's a different plant from calendula (pot marigold).",
    uses: "Fever (traditional), Colds and flu (traditional), Indigestion (traditional), Skin sores (traditional), Natural yellow color",
    properties: "Source of lutein",
    cautions: "There's no toxicity information on marigold extracts.",
    imageUrl: "/herbs/marigold.jpg",
  },
  {
    name: "Hops",
    scientificName: "Humulus lupulus",
    category: "Medicinal",
    summary: "The cone-like flowers of the hop vine, best known for flavoring beer. Recognised in Europe as a traditional remedy for mild stress and to help sleep.",
    uses: "Sleep, Stress, Beer flavoring",
    properties: "May make you feel sleepy or relaxed (traditional)",
    cautions: "Can make you drowsy, so don't drive if affected; not recommended in pregnancy or for under-12s.",
    imageUrl: "/herbs/hops.jpg",
  },
  {
    name: "Lemongrass",
    scientificName: "Cymbopogon citratus",
    category: "Culinary",
    summary: "A lemon-scented grass, called fever grass in Jamaica, brewed as a tea for colds and flu and used in cooking. In a Brazilian study, lemongrass tea didn't help people sleep or feel less anxious.",
    uses: "Colds and flu (traditional), Fever (traditional), Calming tea (traditional), Cooking",
    properties: "",
    cautions: "Homemade teas can carry pesticide residues or germs; side effects can include bloating and nausea.",
    imageUrl: "/herbs/lemongrass.jpg",
  },
  {
    name: "Amaranth",
    scientificName: "Amaranthus spp.",
    category: "Culinary",
    summary: "A group of fast-growing plants grown worldwide for their nutritious seeds (grain) and leaves, eaten in soups, sauces and baked goods. The grain is rich in protein, and researchers are studying its possible health benefits.",
    uses: "Grain, Leafy vegetable, Nutrition",
    properties: "High in protein and fiber, Antioxidant (in lab tests)",
    cautions: "The reviews used here don't list specific safety concerns; it's mainly eaten as a food.",
    imageUrl: "/herbs/amaranth.jpg",
  },
  {
    name: "Honeysuckle",
    scientificName: "Lonicera japonica",
    category: "Medicinal",
    summary: "Japanese honeysuckle, or jin yin hua, is a widely used herb in traditional Chinese medicine, taken for fevers, sore throats, skin sores and infections. Most research so far is in the lab and in animals.",
    uses: "Fever (traditional), Sore throat (traditional), Skin sores and boils (traditional), Infections (traditional)",
    properties: "May help reduce inflammation (in animal studies), Antiviral (in lab tests)",
    cautions: "In animal studies, extracts interrupted pregnancy; long-term safety hasn't been studied.",
    imageUrl: "/herbs/honeysuckle.jpg",
  },
  {
    name: "Sheep Sorrel",
    scientificName: "Rumex acetosella",
    category: "Medicinal",
    summary: "A common weed best known as one of the four herbs in Essiac, a tea sold as a cancer remedy. The US National Cancer Institute found no good evidence that Essiac works against cancer.",
    uses: "Essiac tea ingredient",
    properties: "",
    cautions: "Essiac isn't FDA-approved to treat cancer or any other condition.",
    imageUrl: "/herbs/sheep-sorrel.jpg",
  },
  {
    name: "Bobinsana",
    scientificName: "Calliandra angustifolia",
    category: "Medicinal",
    summary: "A small Amazonian riverbank tree with pink powder-puff flowers. Indigenous communities use it for tiredness, stomach aches and bites, and it's one of the \"teacher plants\" used alongside ayahuasca. It has barely been studied.",
    uses: "Tiredness (traditional), Stomach ache (traditional), Bites (traditional), Ayahuasca ceremonies",
    properties: "",
    cautions: "Its safety hasn't been studied.",
    imageUrl: "/herbs/bobinsana.jpg",
  },
  {
    name: "Clematis Root",
    scientificName: "Clematis chinensis",
    category: "Medicinal",
    summary: "The root of a Chinese climbing plant, known as wei ling xian, used in traditional Chinese medicine for rheumatic joint pain and stiff, numb limbs. It can be toxic.",
    uses: "Joint pain (traditional), Stiff limbs (traditional), Numbness (traditional)",
    properties: "May help reduce inflammation (in lab and animal studies)",
    cautions: "Toxicity studies report mouth burning, belly pain, severe diarrhea, breathing problems and death.",
    imageUrl: "/herbs/clematis-root.jpg",
  },
  {
    name: "Indian Trumpet Tree",
    scientificName: "Oroxylum indicum",
    category: "Medicinal",
    summary: "An Asian tree with huge sword-shaped seed pods, called shyonaka in Ayurveda, where its root bark and seeds are used for diarrhea, fever, coughs and joint pain. Its safety hasn't been studied in detail.",
    uses: "Diarrhea (traditional), Fever (traditional), Cough (traditional), Joint pain (traditional), Ayurvedic tonics",
    properties: "Antioxidant (in lab tests), May help reduce inflammation (in lab and animal studies)",
    cautions: "No detailed safety studies have been published.",
    imageUrl: "/herbs/indian-trumpet-tree.jpg",
  },
  {
    name: "Hyssop",
    scientificName: "Hyssopus officinalis",
    category: "Medicinal",
    summary: "A blue-flowered herb of the mint family, used for colds, coughs and poor appetite and as a flavoring. Its essential oil can cause seizures at high doses.",
    uses: "Colds (traditional), Cough (traditional), Loss of appetite (traditional), Flavoring",
    properties: "Kills bacteria and fungi (in lab tests)",
    cautions: "High doses of the essential oil can cause seizures; little is known about safety in pregnancy.",
    imageUrl: "/herbs/hyssop.jpg",
  },
  {
    name: "Jasmine",
    scientificName: "Jasminum sambac",
    category: "Medicinal",
    summary: "Arabian jasmine, a fragrant white flower. Jasmine flowers placed on the breasts have been tested as a way to stop breast milk after childbirth, and a trial found they worked about as well as a standard medicine.",
    uses: "Stopping breast milk, Fragrance",
    properties: "May reduce breast milk (one trial)",
    cautions: "Jasmine flowers placed on the breasts reduced breast milk in a trial.",
    imageUrl: "/herbs/jasmine.jpg",
  },
  {
    name: "Alysicarpus Vaginalis",
    scientificName: "Alysicarpus vaginalis",
    category: "Medicinal",
    summary: "A small creeping plant of the pea family, called medina in Jamaica, where it's one of the herbs boiled into the \"strong back\" root tonic drunk by men for stamina. Research so far is only in the lab and in animals.",
    uses: "Root tonic (traditional), Stamina (traditional), Impotence (traditional)",
    properties: "",
    cautions: "Not studied in people.",
    imageUrl: "/herbs/alysicarpus-vaginalis.jpg",
  },
  {
    name: "Sceletium Tortuosum",
    scientificName: "Sceletium tortuosum",
    category: "Medicinal",
    summary: "A South African succulent, known as kanna, chewed for centuries by the San and Khoi peoples to ease hunger, thirst and tiredness and to lift mood. Small trials of an extract found it well tolerated.",
    uses: "Mood (traditional), Stress, Hunger and thirst (traditional), Toothache (traditional)",
    properties: "May improve thinking flexibility (one small trial)",
    cautions: "Studied only in small, short trials in healthy adults.",
    imageUrl: "/herbs/sceletium-tortuosum.jpg",
  },
  {
    name: "Olive Leaf",
    scientificName: "Olea europaea",
    category: "Medicinal",
    summary: "Leaves of the olive tree, recognised in Europe as a traditional remedy for mild water retention. In one trial, olive leaf extract lowered blood pressure about as much as a standard medicine.",
    uses: "Water retention, Blood pressure",
    properties: "May increase urination (traditional), May lower blood pressure (one trial)",
    cautions: "Don't use it if you have severe heart or kidney disease and have been told to limit fluids.",
    imageUrl: "/herbs/olive-leaf.jpg",
  },
  {
    name: "Ceylon Betel Leaf",
    scientificName: "Piper betle",
    category: "Medicinal",
    summary: "The heart-shaped leaf of the betel vine, chewed across Asia and used in folk medicine for the mouth, skin and joints. Betel quid, the leaf wrapped around areca nut, causes mouth cancer.",
    uses: "Fresh breath (traditional), Gums and teeth (traditional), Skin ailments (traditional), Joint pain (traditional)",
    properties: "Kills bacteria and fungi (in lab tests)",
    cautions: "Betel quid made with areca nut, with or without tobacco, causes cancer.",
    imageUrl: "/herbs/ceylon-betel-leaf.jpg",
  },
  {
    name: "Poppy",
    scientificName: "Papaver rhoeas",
    category: "Medicinal",
    summary: "The red corn poppy, a common field weed, used in folk medicine for coughs, sleep problems, diarrhea and pain, and eaten in salads. Eating it has poisoned adults, causing seizures and loss of consciousness. It's a different plant from the opium poppy.",
    uses: "Cough (traditional), Sleep (traditional), Diarrhea (traditional), Pain (traditional)",
    properties: "May make you feel sleepy or relaxed (in animal studies)",
    cautions: "Eating corn poppy has caused poisoning with seizures, confusion and breathing problems.",
    imageUrl: "/herbs/poppy.jpg",
  },
  {
    name: "Cucumber Blossom",
    scientificName: "Cucumis sativus",
    category: "Culinary",
    summary: "The yellow flower of the cucumber vine. The flowers have barely been studied: one lab study found a flower extract slowed some bacteria and fungi, an effect the researchers called almost comparable to standard medicines.",
    uses: "Food",
    properties: "Kills bacteria and fungi (in lab tests)",
    cautions: "The flowers haven't been tested in animals or people.",
    imageUrl: "/herbs/cucumber-blossom.jpg",
  },
  {
    name: "Pine Needles",
    scientificName: "Pinus spp.",
    category: "Medicinal",
    summary: "Needles of pine trees, brewed into a tea popular in Japan, Korea, China and Russia, and used in folk medicine for coughs, colds and flu. Some pines contain a substance that causes miscarriage in cattle.",
    uses: "Coughs and colds (traditional), Flu (traditional), Skin infections and wounds (traditional), Tea",
    properties: "Antioxidant (in lab tests), Kills bacteria and fungi (in lab tests)",
    cautions: "Ponderosa and lodgepole pine needles cause miscarriage in cattle; effects in people haven't been studied.",
    imageUrl: "/herbs/pine-needles.jpg",
  },
  {
    name: "Haritaki",
    scientificName: "Terminalia chebula",
    category: "Medicinal",
    summary: "The dried fruit of the chebulic myrobalan tree, called the \"king of Tibetan medicines\" and one of the three fruits in Triphala. It's used for constipation, digestion, coughs and dental health.",
    uses: "Constipation, Digestion, Cough (traditional), Dental health, Triphala ingredient",
    properties: "Mild laxative (traditional), Kills bacteria (in lab tests), Antioxidant (in lab tests)",
    cautions: "Its long-term safety hasn't been fully studied.",
    imageUrl: "/herbs/haritaki.jpg",
  },
];

async function main() {
  for (const herb of herbs) {
    await prisma.herb.upsert({
      where: { name: herb.name },
      update: herb,
      create: herb,
    });
  }
  console.log(`Seeded ${herbs.length} herbs.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
